### PR TITLE
Debian 9 install

### PR DESCRIPTION
**Pull request by jburel**
Use wheel to install python binding

Check that travis is green

### CODE REVIEW

**Comment by mtbc** [comment]
Diff certainly looks plausible. Curious as to why the replaced `pip install` approach is bad (as it's what I do on OpenStack).

**Comment by joshmoore** [comment]
This method is just much faster since the wheel is pre-built.

**Comment by dominikl** [comment]
Trying to test the PR locally with `./docker-build.sh debian9_nginx` but get:
```
+ echo 'CREATE USER db_user PASSWORD '\''db_password'\'''
No passwd entry for user 'postgres'
The command '/bin/sh -c cd omero-install-test && 	bash install_debian9_nginx.sh && 	bash docker_shutdown_ubuntu.sh' returned a non-zero code: 1
```
Although looks to be unrelated to the PR.

**Comment by mtbc** [comment]
Huh, maybe yet another Docker weirdness? Might be worth trying OpenStack instead.

**Comment by jburel** [comment]
@dominikl thanks I don't think it is a docker weirdness but it is more related to the version of pg used by default in that case. 
Let me review that. This is outside the scope of this PR
If you run ``PGVER=pg96 ./docker-build.sh debian9_nginx`` it will work 

I will fix it in another PR

**Comment by jburel** [comment]
Problem mentioned by @dominikl is not related to this PR and it has now been fixed
see https://github.com/ome/omero-install/pull/191

**Comment by jburel** [comment]
Merging

**Pull request merged**
