### PR TITLE
CentOS 7 use wheel

### PR DESCRIPTION
**Pull request by jburel**
Speed up the installation of ice py
This matches what is currently done for Ubuntu and Debian

### CODE REVIEW

**Comment by joshmoore** [comment]
:+1: though now I'm really starting to wonder if we should maintain a redirect for this.

**Comment by joshmoore** [comment]
(Failure is likely the postgres issue)

**Comment by jburel** [comment]
It is due to pg issue

**Comment by joshmoore** [comment]
I tried to find a way to fix PG but to no avail: https://twitter.com/notjustmoore/status/1146040843607904256

Merging to see the effects on autogen.

**Pull request merged**
