### PR TITLE
Ubuntu 1604

### PR DESCRIPTION
**Pull request by jburel**
This adds support for Ubuntu 16.04
it was mentioned few times on the list/forum
The majority of the step scripts does not need to be modified (excepting pg one). Ideally they could be renamed but we will be moving to ansible so I don't think that is needed

This also sets the default for ice to 3.6

* Check that travis is green.
* run ``autogen.sh`` and check ``walkthrough_ubuntu1604.sh``

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-DEV-merge-homebrew#138](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/138/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/138/consoleText) for more details.
Possible conflicts:
  - PR #134 jburel 'Java9'
    - .travis.yml
  - PR #135 jburel 'Pg96 support'
    - .travis.yml

**Comment by dominikl** [comment]
Tried to run the generated `walkthrough_ubuntu1604.sh`, failed on installing `zeroc-ice-utils`:
```
...
Unpacking zeroc-ice-utils (3.6.3-1000) ...
Replacing files in old package ice35-services (3.5.1-6.4ubuntu1) ...
Replacing files in old package icebox (3.5.1-6.4ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/zeroc-ice-utils_3.6.3-1000_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/slice2html', which is also in package ice35-translators 3.5.1-6.4ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package zeroc-ice-utils-java.
Preparing to unpack .../zeroc-ice-utils-java_3.6.3-1000_all.deb ...
Unpacking zeroc-ice-utils-java (3.6.3-1000) ...
Selecting previously unselected package zeroc-ice-all-runtime.
Preparing to unpack .../zeroc-ice-all-runtime_3.6.3-1000_all.deb ...
Unpacking zeroc-ice-all-runtime (3.6.3-1000) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for systemd (229-4ubuntu7) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 /var/cache/apt/archives/zeroc-ice-utils_3.6.3-1000_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by dominikl** [comment]
Ah sorry, that's probably because I need your other PR #130, too. Will try again...

**Comment by dominikl** [comment]
Now it's failing on a different package ` ice35-translators` :
```
...
Unpacking ice35-translators (3.5.1-6.4ubuntu1) ...
Replaced by files in installed package libzeroc-ice-java (3.6.3-1000) ...
dpkg: error processing archive /var/cache/apt/archives/ice35-translators_3.5.1-6.4ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/slice2html', which is also in package zeroc-ice-utils 3.6.3-1000
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

**Comment by jburel** [comment]
why do you need https://github.com/ome/omero-install/pull/130?

**Comment by jburel** [comment]
to build with ice 3.6
``ICEVER=ice36  ./docker-build.sh ubuntu1604_nginx/``
with 3.5
``ICEVER=ice35  ./docker-build.sh ubuntu1604_nginx/``

**Comment by dominikl** [comment]
Thanks. ubuntu1604 docker build seems to work, omero server and web is running. Good to merge. Will try again with a local ubuntu1604 vm again, too.

**Comment by dominikl** [comment]
Still get the dpkg error in ubuntu vm. Anyway, docker build works 👍

**Pull request merged**
