### PR TITLE
Homebrew: add OMERO 5.2 installation script

### PR DESCRIPTION
**Pull request by sbesson**
To be tested together with https://github.com/ome/homebrew-alt/pull/92 by https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-homebrew

### CODE REVIEW

**Comment by sbesson** [comment]
@aleksandra-tarkowska: GOT IT!!
The  `SCRIPT_NAME` variable set by the script was conflicting with Django/Nginx. And the previous formula was tested with nginx/FastCGI which is why we never got exposed to this error before. I would expect the last commit to turn https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ green!

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/14 finally green

**Comment by aleksandra-tarkowska** [comment]
I wouldn't ever guess. But I really cannot remember why do we do https://github.com/openmicroscopy/openmicroscopy/pull/3947/files#diff-ad256e5e06d156adf521e47a4cdd8c37R442.

**Comment by joshmoore** [comment]
Congrats, @sbesson. @aleksandra-tarkowska, is there a card for the `SCRIPT_NAME` follow-up?

Looking at the 51 / 52 diff:

```
2c2
< # Main OMERO/Bio-Formats installation script
---
> # Main OMERO installation script
10c10
< export SCRIPT_NAME=${SCRIPT_NAME:-OMERO.sql}
---
> export PSQL_SCRIPT_NAME=PSQL_SCRIPT_NAME:-OMERO.sql}
18,25d17
< # Bio-Formats installation
< ###################################################################
< 
< # Install Bio-Formats
< bin/brew install bioformats51
< VERBOSE=1 bin/brew test bioformats51
< 
< ###################################################################
30,40c22,25
< OMERO_PYTHONPATH=$(bin/brew --prefix omero51)/lib/python
< if [ "$ICE" == "3.4" ]; then
<     bin/brew install omero51 --with-ice34 --with-nginx
<     ICE_HOME=$(bin/brew --prefix zeroc-ice34)
<     export PYTHONPATH=$OMERO_PYTHONPATH:$ICE_HOME/python
<     export DYLD_LIBRARY_PATH=$ICE_HOME/lib
< else
<     bin/brew install omero51 --with-nginx --with-cpp
<     export PYTHONPATH=$OMERO_PYTHONPATH
< fi
< VERBOSE=1 bin/brew test omero51
---
> OMERO_PYTHONPATH=$(bin/brew --prefix omero52)/lib/python
> bin/brew install omero52 --with-nginx --with-cpp
> export PYTHONPATH=$OMERO_PYTHONPATH
> VERBOSE=1 bin/brew test omero52
45a31
> bin/pip install -r $(bin/brew --prefix omero52)/requirements.txt
49c35
< export ICE_CONFIG=$(bin/brew --prefix omero51)/etc/ice.config
---
> export ICE_CONFIG=$(bin/brew --prefix omero52)/etc/ice.config
71,73c57,59
< bin/omero db script --password $ROOT_PASSWORD -f $SCRIPT_NAME
< bin/psql -h localhost -U db_user omero_database < $SCRIPT_NAME
< rm $SCRIPT_NAME
---
> bin/omero db script --password $ROOT_PASSWORD -f $PSQL_SCRIPT_NAME
> bin/psql -h localhost -U db_user omero_database < $PSQL_SCRIPT_NAME
> rm $PSQL_SCRIPT_NAME
95,98c81
< bin/omero config set omero.web.application_server "fastcgi-tcp"
< bin/omero config set omero.web.debug True
< bin/omero web config nginx-development --http $HTTPPORT > /usr/local/etc/nginx/omero.conf
< nginx -c /usr/local/etc/nginx/omero.conf
---
> bin/omero web config nginx-development --http $HTTPPORT > $(bin/brew --prefix omero52)/etc/nginx.conf
99a83
> nginx -c $(bin/brew --prefix omero52)/etc/nginx.conf
103c87
< sleep 10
---
> sleep 30
110a95
> nginx -c $(bin/brew --prefix omero52)/etc/nginx.conf -s stop
112d96
< nginx -c /usr/local/etc/nginx/omero.conf -s stop
```

this will start to fail once https://github.com/openmicroscopy/openmicroscopy/pull/4301 is merged. Holding off briefly.

**Comment by sbesson** [comment]
As mentioned to @joshmoore, this will start failing once https://github.com/ome/homebrew-alt/pull/92 is updated to consume 5.2.0 with the new requirements style. I can push an extra commit to this PR to fix the requirements when the Homebrew formula is bump.

**Comment by aleksandra-tarkowska** [comment]
@sbesson that would be great. ``SCRIPT_NAME`` is one of the env variable consumed by Django and shouldn't be used for anything else

**Comment by sbesson** [comment]
@aleksandra-tarkowska: as a trivial RFE, maybe we could detect and warn in the CLI web plugin if `SCRIPT_NAME` is set ?

**Comment by aleksandra-tarkowska** [comment]
Sure, can do it

**Comment by joshmoore** [comment]
:thumbsup:

**Pull request merged**
