### PR TITLE
Recap Pillow

### PR DESCRIPTION
**Pull request by jburel**
Recap Pillow to 2.9.0
This PR might have to be merged before release of 5.2.3 depending on outcome of https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-Python27/

### CODE REVIEW

**Comment by atarkowska** [comment]
it failed 16:38:11 test/integration/test_bigImages.py::TestFigureExportScripts::testRenderRegion FAILED

https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-Python27/lastCompletedBuild/testReport/OmeroPy.test.integration.test_bigImages/TestFigureExportScripts/testRenderRegion/

**Comment by atarkowska** [comment]
Pillow adjusted in https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-Python27/199/ should be green then

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-integration-Python27/199/ is green

**Comment by atarkowska** [comment]
ok then this is good to merge

**Pull request merged**
