### PR TITLE
fix homebrew web login test

### PR DESCRIPTION
**Pull request by atarkowska**
This PR is an attempt to fix Homebrew test job that may silently failing on logging in to webclient, see https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/149/console

To test check console https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper

### CODE REVIEW

**Comment by atarkowska** [comment]
tested vi https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/150/console

**Comment by atarkowska** [comment]
This PR is waiting for https://github.com/ome/omero-install/pull/99 to reuse new script

**Comment by atarkowska** [comment]
excluding for the moment as the syntax is wrong https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/152/console

```
+ bash WEB_HOST=locahost:8081 OMERO_ROOT_PASS=omero ../linux/test/test_login_to_web.sh
bash: WEB_HOST=locahost:8081: No such file or directory
```

**Comment by joshmoore** [comment]
`env W=l.. O=o.. bash w...sh`

**Comment by atarkowska** [comment]
thank you ;-)

**Comment by atarkowska** [comment]
this will never pass travis

**Comment by atarkowska** [comment]
Fixed https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/157/console

**Comment by jburel** [comment]
```
+ echo 'Perform login ...'
Perform login ...
++ curl -i -k -s -c cookies.txt -b cookies.txt -e http://localhost:8081/webclient/login/ -d 'csrfmiddlewaretoken=aVqrt1ciBs3IPSNfpDqEdukFd4Ey2XYg&username=root&password=omero_root_password&server=1' -X POST http://localhost:8081/webclient/login/
+ RSP='HTTP/1.1 302 FOUND
Server: nginx/1.8.1
Date: Mon, 18 Apr 2016 07:46:31 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Cookie
Location: http://localhost:8081/webclient/
Set-Cookie: sessionid=szo815j3sja1nk5t1210r9wkkg3m9wr7; httponly; Path=/

'
+ grep -q id_server
+ echo 'You are logged in!'
You are logged in!
+ echo 'Perform logout ...'
Perform logout ...
+ curl -i -k -s -c cookies.txt -b cookies.txt -e http://localhost:8081/webclient/login/ -d csrfmiddlewaretoken=aVqrt1ciBs3IPSNfpDqEdukFd4Ey2XYg -X POST http://localhost:8081/webclient/logout/
HTTP/1.1 302 FOUND
Server: nginx/1.8.1
Date: Mon, 18 Apr 2016 07:46:32 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Location: http://localhost:8081/webclient/
Set-Cookie: sessionid=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/

+ echo 'You are logged out!'
You are logged out!
```

it works

**Comment by jburel** [comment]
Thanks @aleksandra-tarkowska. Merging

**Pull request merged**
