### PR TITLE
change link

### PR DESCRIPTION
**Pull request by jburel**
Modify the link so it can be built using the artifacts from GitHub
The only downside is that the URL will need to be modified every time

### CODE REVIEW

**Comment by manics** [comment]
https://github.com/ome/omego/pull/127 could help. It currently requires the full tag, but in future this could be changed to list all tags and do semver-based matching of partial versions.

**Comment by jburel** [comment]
@manics I used omego previously for merge-build etc. Happy to bring that back in

**Comment by manics** [comment]
We could get this PR in now assuming everything works, then switch to omego separately

**Comment by jburel** [comment]
Travis is green so it works!!

**Review by manics — APPROVED** [review]

**Comment by jburel** [comment]
Another option will be to drop the version from the zip attached on GitHub and use

https://github.com/ome/openmicroscopy/releases/latest/download/OMERO.server.zip

**Pull request merged**
