### PR TITLE
Java11 support

### PR DESCRIPTION
**Pull request by jburel**
Add support for Java 11 for CentOS 7, Debian9 and Ubuntu 16.04
openjdk is not available yet on all OS.

Installation is tested via travis
Check Ubuntu or Debian locally 
e.g. ``JAVAVER=oracle11 ./docker-build.sh debian9_nginx``
and check that the server starts correctly

### CODE REVIEW

**Comment by dominikl** [comment]
Tested with debian, no problems:
```
ls29139:test dlindner$ docker run --rm -it -p 8080:80 -p 4063:4063 -p 4064:4064  omero_install_test_debian9_nginx
[ ok ] Starting PostgreSQL 9.6 database server: main.
Starting omero: OMERO.server
[ ok ] Starting nginx: nginx.
Starting omero-web: OMERO.web
root@7772cf96d0d2:/# java --version
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```
👍

**Comment by jburel** [comment]
@dominikl I have now added support for openjdk 11 on Debian 9. The installation will be tested via travis 
but could you run the following
``JAVAVER=openjdk11 ./docker-build.sh debian9_nginx``
and check the version

**Comment by dominikl** [comment]
Works as well 👍 
```
[ ok ] Starting PostgreSQL 9.6 database server: main.
Starting omero: OMERO.server
[ ok ] Starting nginx: nginx.
Starting omero-web: OMERO.web
root@c4b7b45af9dd:/# java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Debian-2bpo91)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Debian-2bpo91, mixed mode, sharing)
```

**Comment by jburel** [comment]
Thanks @dominikl

**Pull request merged**
