### PR TITLE
Setup selinux on Centos 7 nginx

### PR DESCRIPTION
**Pull request by manics**
If SELinux is enabled on CentOS7 you need to run this. I haven't looked at Apache.

To test you'll need a Centos7 VM with SELinux enabled, then run `install_centos7_nginx.sh` as root

### CODE REVIEW

**Comment by jburel** [comment]
@manics: did that get reviewed?

**Comment by ximenesuk** [comment]
@jburel, no other work go in the way. I've re-listed for tomorrow and will do this first thing.

**Comment by jburel** [comment]
@ximenesuk: I missed it in today's standup list, so wanted to make sure it is reviewed
Thanks

**Comment by ximenesuk** [comment]
I'm afraid I am going to have to pass on this one. The morning was wiped out by the lack of an external network and when I have now got around to looking at it I have no idea how to get a centos7 docker up and running. If anyone is able to do this quickly then I'll defer to them.

**Comment by jburel** [comment]
@ximenesuk I will have a look tonight

**Comment by manics** [comment]
You'll have to test it in a CentOS 7 VM, selinux is a kernel level feature and difficult to get working in Docker

**Comment by ximenesuk** [comment]
Ah, sorry I misunderstood the PR description I assumed I could test via a docker.

**Comment by dominikl** [comment]
Tested with Centos-7-x86_64-1503-01 , install scripts aborts with an error about a missing lib _libunwind_ .

```
...
+ OMERO.server/bin/omero web config nginx --http 80
+ bash -eux step05_centos7_nginx.sh
+ yum -y install nginx python-gunicorn
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.melbourne.co.uk
 * epel: mirror.bytemark.co.uk
 * extras: mirror.bytemark.co.uk
 * updates: mirrors.melbourne.co.uk
Resolving Dependencies
--> Running transaction check
---> Package nginx.x86_64 1:1.6.3-7.el7 will be installed
--> Processing Dependency: nginx-filesystem = 1:1.6.3-7.el7 for package: 1:nginx-1.6.3-7.el7.x86_64
--> Processing Dependency: nginx-filesystem for package: 1:nginx-1.6.3-7.el7.x86_64
--> Processing Dependency: GeoIP for package: 1:nginx-1.6.3-7.el7.x86_64
--> Processing Dependency: libprofiler.so.0()(64bit) for package: 1:nginx-1.6.3-7.el7.x86_64
--> Processing Dependency: libGeoIP.so.1()(64bit) for package: 1:nginx-1.6.3-7.el7.x86_64
---> Package python-gunicorn.noarch 0:18.0-2.el7 will be installed
--> Running transaction check
---> Package GeoIP.x86_64 0:1.5.0-9.el7 will be installed
---> Package gperftools-libs.x86_64 0:2.4-5.el7 will be installed
--> Processing Dependency: libunwind.so.8()(64bit) for package: gperftools-libs-2.4-5.el7.x86_64
---> Package nginx-filesystem.noarch 1:1.6.3-7.el7 will be installed
--> Finished Dependency Resolution
Error: Package: gperftools-libs-2.4-5.el7.x86_64 (epel)
           Requires: libunwind.so.8()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by dominikl** [comment]
Apparently this is going to be fixed in Centos 7.2: https://www.centos.org/forums/viewtopic.php?f=47&t=55325
Going to try if the suggested workaround will work.

**Comment by manics** [comment]
It's because a package was moved from an add-on repo (epel) into the main repo, and things are out of sync until the next release http://comments.gmane.org/gmane.linux.redhat.fedora.devel/214645

**Comment by jburel** [comment]
@dominikl I got the same error when working on Pillow version 
reported here https://trello.com/c/Zr30Nu1T/96-pillow-version

**Comment by jburel** [comment]
Since we are using the centos7 script in our doc so we will need to have a workaround or do not suggest nginx for 5.2.1

**Comment by dominikl** [comment]
Install script works fine with the suggested workaround, just add `yum -y update && yum-config-manager --enable cr` as first command to `step01_centos7_deps.sh` to enable the continuous release repository.

**Comment by jburel** [comment]
@dominikl: do you want to open a PR indicating that it is a workaround?

**Comment by dominikl** [comment]
Done  #66

**Comment by dominikl** [comment]
Still one issue left, OMERO.web login looks like that (static content missing?):
screen shot 2015-12-09 at 11 30 28

**Comment by jburel** [comment]
that's a streamline login page!!!

**Comment by jburel** [comment]
@manics: will you have time to look at it in this PR?

**Comment by manics** [comment]
```
$ sudo -i
# getenforce
Enforcing
# yum install -y git
# yum upgrade

# git clone https://github.com/ome/omero-install.git
# cd omero-install/
# git fetch origin pull/63/head:pr63
# git config user.email "test@example.com"
# git config user.name test
# git merge pr63
# cd linux/
# bash install_centos7_nginx.sh
# systemctl start omero
# systemctl start omero-web
```

Works for me. Can you check `/var/log/messages`, `/var/log/nginx/error.log`, and either look at `/var/log/audit/audit.log` or run `audit2why` as root (which should interpret `/var/log/audit/audit.log` for you)?

**Comment by dominikl** [comment]
Tried again, restarted, same result. `/var/log/messages` doesn't contain anything useful, `/var/log/nginx/error.log` is empty and `audit2why` doesn't do anything but `/var/log/audit/audit.log` apparently also doesn't contain anything useful.

**Comment by joshmoore** [comment]
Following https://www.openmicroscopy.org/site/support/omero5.2-staging/sysadmins/unix/server-linux-walkthrough.html worked for me today (barring a few doc-level confusions). My workflow was:

```
$ mkdir /tmp/c7
$ cd /tmp/c7
$ wget $SERVER_ZIP
$ brew install vagrant
$ vagrant init centos/7
$ vi Vagrantfile # increase memory and open ports
$ grep -E "(10080|2048)" Vagrantfile
  config.vm.network "forwarded_port", guest: 80, host: 10080
     vb.memory = "2048"
$ vagrant up
$ vagrant ssh # Follow install instructions
```

Primarily gotcha was that the instructions say "test http://localhost" but that doesn't work until selinux has been run, so I'd suggest moving that forward. Merging.

**Pull request merged**
