### PR TITLE
Cleanup Homebrew scripts post branch split

### PR DESCRIPTION
**Pull request by sbesson**
As we are using a multiple branches strategy in sync with openmicroscopy and
ome-documentation, there is no reason to maintain legacy installation scripts.

### CODE REVIEW

**Comment by sbesson** [comment]
@ximenesuk @jburel @manics: should we adopt the same naming convention in Homebrew as in linux, e.g. `step00_cleanup_homebrew`, `step_01_install_homebrew`... Also should we go for versionless names i.e. `install_omero`?

**Comment by jburel** [comment]
@sbesson: I will vote for unification and that could make things easier for docs
cc @hflynn

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/33/. For the renaming, I'll likely wait until we have come to an agreement on Linux.

**Comment by joshmoore** [comment]
Perhaps we could also add to the renaming effort:
- versions in script names or not (we currently have one with `51`)
- update to README (which currently skips bioformats)

**Pull request merged**
