### PR TITLE
Set permissions on etc and var

### PR DESCRIPTION
**Pull request by manics**
Update walkthrough to set permissions on `etc` and `var`: https://github.com/openmicroscopy/ome-documentation/pull/1210

### CODE REVIEW

**Comment by manics** [comment]
Pushed. Note that the Apache instructions are now invalid until 5.1.2 is released.

**Comment by joshmoore** [comment]
Fair enough. Merging though for RC day. Is there anything that needs to be re-run on the docs side? cc: @sbesson

**Comment by sbesson** [comment]
We should be fine as https://ci.openmicroscopy.org/job/OMERO-5.1-latest-docs-autogen/ is polling changes on this repo. See https://ci.openmicroscopy.org/job/OMERO-5.1-latest-docs-autogen/658/ and https://github.com/openmicroscopy/ome-documentation/pull/1218/files.

**Comment by joshmoore** [comment]
+1 for
https://github.com/openmicroscopy/ome-documentation/pull/1218/files#diff-a9a8df4a219035e65ba917735729a99b

but does a new file need to be added?

**Comment by sbesson** [comment]
Ah right, will open a PR this morning about the new file.

**Pull request merged**
