### PR TITLE
ice36 build link

### PR DESCRIPTION
**Pull request by jburel**
Update link to ice 3.6 build

To test, run for example

`ICEVER=ice36 ./docker-build.sh ubuntu1404_nginx`

### CODE REVIEW

**Comment by atarkowska** [comment]
```
+ SERVER=http://downloads.openmicroscopy.org/omero/5.2.3-rc1/artifacts/OMERO.server-5.2.3-rc1-ice36-b21.zip
+ unzip -q 'OMERO.server*'
unzip:  cannot find or open OMERO.server*, OMERO.server*.zip or OMERO.server*.ZIP.
```

**Comment by jburel** [comment]
we will need to do manually, since rc are private (behind firewall)
The link will be updated later on when the redirect is in place cc @sbesson.

**Comment by atarkowska** [comment]
is this the last PR for 5.2.3 release? if so could we tag that repo once this is merged please?

**Comment by jburel** [comment]
We tag the repo as part of the release.
This is one of the post acceptance step see https://trello.com/c/ZHMpB9FW/11-release-acceptance

**Comment by atarkowska** [comment]
failing with

```
2016-05-02 08:38:08 (34.3 MB/s) - ‘server-ice36.zip’ saved [152634977/152634977]

+ unzip -q 'OMERO.server*'
unzip:  cannot find or open OMERO.server*, OMERO.server*.zip or OMERO.server*.ZIP.

No zipfiles found.
```

but

```
SERVER=http://downloads.openmicroscopy.org/latest/omero5.2/server-ice35.zip
wget -O OMERO.server-ice36.zip $SERVER 
```

should do the trick

**Comment by jburel** [comment]
it might be good to review the way server-ice36.zip has been created to unify ice 3.5 and ice 3.6 case
cc @sbesson

**Comment by atarkowska** [comment]
works as expected now

```
+ '[' ice36 = ice36 ']'
+ cd /home/omero
+ SERVER=http://downloads.openmicroscopy.org/latest/omero5.2/server-ice36.zip
+ wget http://downloads.openmicroscopy.org/latest/omero5.2/server-ice36.zip
--2016-05-02 08:38:04--  http://downloads.openmicroscopy.org/latest/omero5.2/server-ice36.zip
Resolving downloads.openmicroscopy.org (downloads.openmicroscopy.org)... 134.36.65.239
Connecting to downloads.openmicroscopy.org (downloads.openmicroscopy.org)|134.36.65.239|:80... connected.
HTTP request sent, awaiting response... 303 See Other
Location: http://downloads.openmicroscopy.org/omero/5.2.3-rc1/artifacts/OMERO.server-5.2.3-rc1-ice36-b21.zip [following]
--2016-05-02 08:38:04--  http://downloads.openmicroscopy.org/omero/5.2.3-rc1/artifacts/OMERO.server-5.2.3-rc1-ice36-b21.zip
Connecting to downloads.openmicroscopy.org (downloads.openmicroscopy.org)|134.36.65.239|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 152634977 (146M) [application/zip]
Saving to: ‘server-ice36.zip’
...
149050K .......                                               100% 39.5M=4.1s

2016-05-02 09:25:08 (35.9 MB/s) - ‘OMERO.server-ice36.zip’ saved [152634977/152634977]

+ unzip -q OMERO.server-ice36.zip
+ ln -s OMERO.server-5.2.3-rc1-ice36-b21/ OMERO.server
+ OMERO.server/bin/omero config set omero.data.dir /OMERO

```

**Comment by atarkowska** [comment]
good to merge

**Comment by joshmoore** [comment]
big :thumbsup:

**Pull request merged**
