### PR TITLE
ubuntu 1504

### PR DESCRIPTION
**Pull request by jburel**
Follow installation of ubuntu1404 (nginx)
install java 1.8 instead of java 1.7. The rest is unchanged.
Apache support will be added following work by @ximenesuk

### CODE REVIEW

**Comment by ximenesuk** [comment]
The end of life for 15.04 is January 2016, do we we really need to support this version?

**Comment by jburel** [comment]
This is mainly for testing in case someone asks

**Comment by ximenesuk** [comment]
Yes but then by that argument we must support 12.04 and 15.10. Surely we should only support LTS as we do with other packages?

**Comment by jburel** [comment]
Will check 12.04 and close this one

**Pull request closed without merging**
