### PR TITLE
Correct name of PostgreSQL setup script.

### PR DESCRIPTION
**Pull request by mtbc**
```
$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 
$ ls -l /usr/pgsql-10/bin/postgresql*setup
-rwxr-xr-x. 1 root root 9419 May  8 10:25 /usr/pgsql-10/bin/postgresql-10-setup
$ 
```

### CODE REVIEW

**Comment by jburel** [comment]
Strange: Travis has always been green and PG10 is the testing matrix
see https://github.com/ome/omero-install/blob/develop/.travis.yml#L5

**Comment by joshmoore** [comment]
Feels vaguely similar to the recent issue where a bash script was failing silently. I imagine adding `set -e` to the proper locations would detect this type of thing.

**Comment by mtbc** [comment]
No idea what the Travis failures are about.

**Comment by joshmoore** [comment]
Looks like it never found `OMERO.blitz now accepting connections` in quite a few of the servers. Perhaps that script could cat the Blitz-0.log file on failure?

**Comment by jburel** [comment]
Having a closer look at the file, the reason travis did not fail is b/c the command is not run in docker!
that's the commands run if docker container
```
su - postgres -c "/usr/pgsql-10/bin/initdb -D /var/lib/pgsql/10/data --encoding=UTF8"
echo "listen_addresses='*'" >> /var/lib/pgsql/10/data/postgresql.conf
```

**Comment by jburel** [comment]
Thanks for spotting that error

**Comment by joshmoore** [comment]
Is this a good target for trying to pin the postgres version?

**Comment by mtbc** [comment]
(I don't know but happy to accept whatever you and @jburel think wise.)

**Comment by jburel** [comment]
I think we can merge this PR as it is for 5.5.1
The change is not tested in travis and it will correct our doc.
Let's hope a new pg version will be released in the coming days. Otherwise we will have to pin the version (this will require another doc release)

**Comment by joshmoore** [comment]
Merging along with https://github.com/ome/omero-install/pull/208#issuecomment-507703522

**Pull request merged**
