### PR TITLE
Centos6 ius

### PR DESCRIPTION
**Pull request by jburel**
Refactor code to follow the step approach
To test nginx:
- run `./docker-build.sh centos6_py27_ius_nginx/`
- when complete,  `docker run --rm -it -p 8080:80 -p 4063:4063 -p 4064:4064 omero_install_test_centos6_py27_ius_nginx`
- Check that omero and web are running

To test apache22:
- run `./docker-build.sh centos6_py27_ius_apache22/`
- when complete,  `docker run --rm -it -p 8080:80 -p 4063:4063 -p 4064:4064 omero_install_test_centos6_py27_ius_apache22`
- Check that omero and web are running

To test apache24:
- run `./docker-build.sh centos6_py27_ius_apache24/`
- when complete,  `docker run --rm -it -p 8080:80 -p 4063:4063 -p 4064:4064 omero_install_test_centos6_py27_ius_apache24`
- Check that omero and web are running

I have added a "virtual dependencies" step to try to match the current documentation.

still TODO:
- Update readme. To be done in https://github.com/ome/omero-install/pull/81 discussed with @ximenesuk 
- modify `.travis.yml`

The changes above will conflict with existing PRs.

### CODE REVIEW

**Comment by ximenesuk** [comment]
All three builds work and deploy with no problem.The code changes look okay. Good to merge unless there are any further changes to be made in this PR.

**Comment by jburel** [comment]
I will have to add new env to `.travis.yml`

**Comment by jburel** [comment]
all the "_ius"  now passing on Travis.
Note that this PR will conflict tomorrow with #80 
When this is merged, I will add support for web in #80 after rebase and clean up  a bit more the travis file

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper#82](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/82/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/82/consoleText) for more details.
Possible conflicts:
- PR #80 jburel 'Webapp'
  - .travis.yml

**Comment by jburel** [comment]
travis is finally green

**Comment by joshmoore** [comment]
Merging based on the status travis since only configurations were added:

screen shot 2016-01-14 at 09 06 42

:thumbsup:

**Pull request merged**
