### PR TITLE
Change CentOS 6 walkthrough to install Python 2.7 and recompile Ice

### PR DESCRIPTION
**Pull request by manics**
Note this adds two new files, so if it is merged they'll need to be added to the docs walkthrough.

```
================================================================================
OMERO Diagnostics 5.2.0-ice35-b12
================================================================================
        
Commands:   java -version                  1.8.0     (/usr/bin/java)
Commands:   python -V                      2.7.5     (/opt/rh/python27/root/usr/bin/python -- 2 others)
Commands:   icegridnode --version          3.5.1     (/opt/Ice-3.5.1/bin/icegridnode)
Commands:   icegridadmin --version         3.5.1     (/opt/Ice-3.5.1/bin/icegridadmin)
Commands:   psql --version                 9.4.5     (/usr/bin/psql)

Server:     icegridnode                    running
Server:     Blitz-0                        active (pid = 750, enabled)
Server:     DropBox                        active (pid = 788, enabled)
Server:     FileServer                     active (pid = 797, enabled)
Server:     Indexer-0                      active (pid = 802, enabled)
Server:     MonitorServer                  active (pid = 942, enabled)
Server:     OMERO.Glacier2                 active (pid = 803, enabled)
Server:     OMERO.IceStorm                 active (pid = 845, enabled)
Server:     PixelData-0                    active (pid = 852, enabled)
Server:     Processor-0                    active (pid = 882, enabled)
Server:     Tables-0                       active (pid = 936, enabled)
Server:     TestDropBox                    inactive (enabled)

Log dir:    /home/omero/OMERO.server/var/log exists
Log files:  Blitz-0.log                    696.0 KB      errors=16   warnings=0   
Log files:  DropBox.log                    1.0 KB       
Log files:  FileServer.log                 0.0 KB       
Log files:  Indexer-0.log                  1.0 KB       
Log files:  MonitorServer.log              1.0 KB       
Log files:  OMEROweb.lock                  0.0 KB       
Log files:  OMEROweb.log                   2.0 KB        errors=0    warnings=1   
Log files:  OMEROweb_brokenrequest.lock    0.0 KB       
Log files:  OMEROweb_brokenrequest.log     0.0 KB       
Log files:  PixelData-0.log                2.0 KB       
Log files:  Processor-0.log                56.0 KB       errors=16   warnings=0   
Log files:  Tables-0.log                   0.0 KB       
Log files:  TestDropBox.log                n/a
Log files:  master.err                     0.0 KB       
Log files:  master.out                     0.0 KB       
Log files:  Total size                     0.76 MB


Environment:OMERO_HOME=(unset)             
Environment:OMERO_NODE=(unset)             
Environment:OMERO_MASTER=(unset)           
Environment:OMERO_USERDIR=(unset)          
Environment:OMERO_TMPDIR=(unset)           
Environment:PATH=/opt/Ice-3.5.1/bin:/opt/rh/python27/root/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/omero/bin 
Environment:PYTHONPATH=/opt/Ice-3.5.1/python: 
Environment:ICE_HOME=(unset)               
Environment:LD_LIBRARY_PATH=/opt/Ice-3.5.1/lib64:/opt/Ice-3.5.1/lib:/opt/rh/python27/root/usr/lib64 
Environment:DYLD_LIBRARY_PATH=(unset)      

OMERO SSL port:4064                           
OMERO TCP port:4063                           
OMERO data dir:'/OMERO'                       Exists? True	Is writable? True
OMERO temp dir:'/home/omero/omero/tmp'        Exists? True	Is writable? True   (Size: 0)

JVM settings: Blitz-${index}                -Xmx7200m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Indexer-${index}              -Xmx4800m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: PixelData-${index}            -Xmx7200m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Repository-${index}           -Xmx4800m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions

OMERO.web status... [RUNNING] (PID 1166)
Django version: 1.8.6
```

### CODE REVIEW

**Comment by manics** [comment]
This works for nginx, it doesn't work for apache (need to sort out Python 2.7 `mod_wsgi`)

**Comment by rleigh-dundee** [comment]
Looks fine to me on a readthrough.  Is this tested on any of our infrastructure or does it require manual testing?

**Comment by manics** [comment]
You can test it manually with docker:
```
cd linux/test
./docker-build.sh centos6 ...
```

**Comment by manics** [comment]
The last commit 2240190 should fix centos6-apache, except it's uncovered an OMERO bug (Apache 2.2 and 2.4 configs are slightly different).

**Comment by manics** [comment]
See #45 instead.

**Pull request closed without merging**
