### PR TITLE
Update file

### PR DESCRIPTION
**Pull request by jburel**
Update file to fix travis

Check that the following error is no longer in the log
```
travis_time:start:1548f5e3
[0K$ ./autogenerate.sh
centos7
centos6_py27
sed: -e expression #1, char 4: invalid usage of line address 0
sed: -e expression #1, char 4: invalid usage of line address 0
centos6_py27_ius
ubuntu1404
debian8
ubuntu1604
debian9
```

### CODE REVIEW

**Comment by joshmoore** [comment]
What's the `diff` to the web docs with this PR?

**Comment by mtbc** [comment]
Now runs cleanly:

```
$ ./autogenerate.sh 
centos7
centos6_py27
centos6_py27_ius
ubuntu1404
debian8
ubuntu1604
debian9
```

:+1:

**Comment by mtbc** [comment]
@joshmoore: As far as I can tell this PR does not change the resulting `walkthrough_*.sh` files.

**Comment by mtbc** [comment]
Update: Sorry, I think my test was flawed, attempting again...

**Comment by mtbc** [comment]
This PR makes a difference to `walkthrough_centos6_py27.sh`:

```diff
138c138
< file=~omero/OMERO.server/share/web/requirements-py27-all.txt
---
> pip install -r  OMERO.server/share/web/requirements-py27.txt
144a145,157
> #start-nginx-install
> cat << EOF > /etc/yum.repos.d/nginx.repo
> [nginx]
> name=nginx repo
> baseurl=http://nginx.org/packages/centos/\$releasever/\$basearch/
> gpgcheck=0
> enabled=1
> EOF
> yum -y install nginx
> #end-nginx-install
> #start-nginx-admin
> mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.disabled
> cp ~omero/OMERO.server/nginx.conf.tmp /etc/nginx/conf.d/omero-web.conf
146c159,160
< 
---
> service nginx start
> #end-nginx-admin
```

I don't know if that is okay and expected.

**Comment by jburel** [comment]
The ouput is correct.
I realised that I did not split the Centos6 py27 (server/web( page but the marker and contents can now be used to do so

**Comment by jburel** [comment]
doc PR opened since we have a missing section following the re-organisation
https://github.com/openmicroscopy/ome-documentation/pull/1775

**Comment by jburel** [comment]
ok to merge so it can be included in the doc via https://github.com/openmicroscopy/ome-documentation/pull/1763

**Pull request merged**
