### PR TITLE
Debian 9: cap table version

### PR DESCRIPTION
**Pull request by jburel**
cc @mtbc @joshmoore

### CODE REVIEW

**Comment by mtbc** [comment]
Probably also fine for Ubuntu 16.

**Comment by jburel** [comment]
I forgot to check. I pushed another commit

**Comment by jburel** [comment]
finally green

**Comment by joshmoore** [comment]
Postponing for a doc release shortly _after_ the upcoming 5.6.1.

**Comment by jburel** [comment]
Merging so it is included in the next doc release

**Pull request merged**
