### PR TITLE
use omego

### PR DESCRIPTION
**Pull request by jburel**
To avoid update of the documentation when new version will be release e.g. 5.7.0
the command will install the latest version in the 5 series

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good to me. Tested it only with Debian10, but as it's all the same for the other distros, that should be enough, isn't it?

**Comment by jburel** [comment]
As discussed in https://github.com/ome/openmicroscopy/issues/6330, the main question is if we want to expose ``omego`` or not in the installation steps

@dominikl the installation is tested via GHA

**Comment by joshmoore** [comment]
For that diff, @jburel, it might not be warranted. Are there other locations you have in mind for using `omego`?

**Comment by jburel** [comment]
Not really, But if we have https://github.com/ome/openmicroscopy/pull/6318 in without any build number
I could easily:
* find the latest version from GitHub
*  build the URL from GitHub.

i.e. no usage of ``omego``
I was planning initially to use it https://github.com/ome/omero-documentation/pull/2261 but I am happy with the alternative solution.

**Comment by jburel** [comment]
Closing this PR. I don't think I will be using ``omego``. With https://github.com/ome/openmicroscopy/pull/6318 in, build number will not be present so it will be possible to build a URL.

**Pull request closed without merging**
