### PR TITLE
OSX renaming

### PR DESCRIPTION
**Pull request by sbesson**
This PR is an attempt at unifying the OSX installation convention with the changes proposed in https://github.com/ome/omero-install/pull/56.

Main changes are:
- the top-level is renamed as `osx` instead of `homebrew` to match with other top-level folders
- the installation scripts to be executed (and exposed in the doc) are renamed as `step*.sh`
- a top-level `install_osx` script is created executes all the steps

Following up this PR, the CI job will need updating to execute something along the lines of

```
cd osx &&  bash cleanup_homebrew.sh && bash install_homebrew.sh
```

The scripts can also be copied as part of the autogen job like Linux walkthrough and directly embedded into the documentation for OSX.

Open questions:
- [x] script termination: with or without `.sh` ?
- [ ] Bio-Formats C++ formula: is this still necessary/appropriate in this repo?
- [x] naming convention: is `install_osx` okay (trying to match the Linux scheme)

### CODE REVIEW

**Comment by joshmoore** [comment]
> naming convention: is install_osx okay (trying to match the Linux scheme)

But the "distribution", so to speak, is "homebrew", no?

**Comment by sbesson** [comment]
@joshmoore yes hesitated treating `homebrew` as the equivalent of `centos6`. happy to do that if it adds clarity.

**Comment by sbesson** [comment]
From https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/38/ it seems like the post install `initdb` command has the wrong encoding (at least on Jenkins). To be discussed with @pwalczysko.

**Comment by sbesson** [comment]
Last commit was successfully tested with https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/39/ and was properly setting the locale in non-interactive shell to initialize the cluster with `UTF-8` /cc @mtbc @joshmoore.

@pwalczysko raised a couple of issues about these scripts/docs which can be addressed in follow-up PRs. Do you want to have a quick review Petr?

**Comment by pwalczysko** [comment]
Improvement suggestions were added as a checklist to https://trello.com/c/IYQaQEDT/65-mac-osx-py2-7-django-1-8-apache-nginx

**Comment by pwalczysko** [comment]
Possible thing to do for me here might be: run `brew install omero` ? Considering my server is already working on my new mac (development server installed from source following the doc http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/server-install-homebrew.html, the question is how would running that script interfere with the existing install ? I really do not want to compromise it, because that is what I want on my machine. Alternatively, I could start a OS X docker, but for this I have to first go through docker workflows on my new machine.

**Comment by pwalczysko** [comment]
from the `omero-install` scripts setup: Yes, I think the creation of the new osx folder improves things. One suggestion, reading:

```
drwxr-xr-x  8 pwalczysko  DUNDEE\Domain Users   272 25 Nov 16:30 ./
drwxr-xr-x  9 pwalczysko  DUNDEE\Domain Users   306 25 Nov 16:30 ../
-rw-r--r--  1 pwalczysko  DUNDEE\Domain Users   587 25 Nov 16:30 README.md
-rwxr-xr-x  1 pwalczysko  DUNDEE\Domain Users   474 25 Nov 16:30 cleanup_homebrew.sh*
-rwxr-xr-x  1 pwalczysko  DUNDEE\Domain Users   405 25 Nov 16:30 install_bioformats_cpp51*
-rw-r--r--  1 pwalczysko  DUNDEE\Domain Users    81 25 Nov 16:30 install_homebrew.sh
-rwxr-xr-x  1 pwalczysko  DUNDEE\Domain Users  1664 25 Nov 16:30 step01_homebrew.sh*
-rwxr-xr-x  1 pwalczysko  DUNDEE\Domain Users  2958 25 Nov 16:30 step02_omero.sh*
```

Why do the scripts `install_homebrew.sh`, `step01_homebrew.sh` and `step02_omero.sh` do not give an idea about which OMERO version is going to be installed ? Compare with `install_bioformats_cpp51`. 

Edit: sorry, understand now that only the `step02_omero.sh` is the script to which my question is relevant, as the other two scripts I mentioned just pave the way for this one ?

**Comment by sbesson** [comment]
@pwalczysko: answering your questions:
- `brew install omero` would install an OMERO under `/usr/local/Cellar/omero`. This is harmless for your existing development server unless you try to start both servers without making sure they are using different ports. This is pretty much the setup I have locally: one Homebrew-installed OMERO for the last release and a development OMERO server
- regarding versioning, we have moved to a development branches system mirroring `openmicroscopy` and `ome-documentation` and this repo should be tagged as part of the release process. As these script will be copied to the documentation, [the documentation page](https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/server-install-homebrew.html) will tell you which version you should expect. The alternative would be to suffix omero with the version but this has costs in terms of maintenance  /cc @ximenesuk @jburel

**Comment by manics** [comment]
The advantage of keeping them unversioned is that it becomes obvious if there's a breaking change in the installation/setup procedure, and reminds us to double check our docs, and potentially highlight the issue in the release notes.

**Comment by pwalczysko** [comment]
@sbesson : checked out your branch, checked that the last commit is as here in the PR. Then see below:

```
[pwalczysko@ls31619 ~/Work/omero-install]$ git branch
* (HEAD detached at seb/osx_renaming)
  master
[pwalczysko@ls31619 ~/Work/omero-install]$ git log
[pwalczysko@ls31619 ~/Work/omero-install]$ brew install omero
==> Installing omero from ome/homebrew-alt
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.openmicroscopy.org/omero/5.2.0/artifacts/openmicroscopy-5.2.0.zip
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: Failed to download resource "omero"
Download failed: http://downloads.openmicroscopy.org/omero/5.2.0/artifacts/openmicroscopy-5.2.0.zip
[pwalczysko@ls31619 ~/Work/omero-install]$ brew install omero
==> Installing omero from ome/homebrew-alt
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.openmicroscopy.org/omero/5.2.0/artifacts/openmicroscopy-5.2.0.zip
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: Failed to download resource "omero"
Download failed: http://downloads.openmicroscopy.org/omero/5.2.0/artifacts/openmicroscopy-5.2.0.zip
[pwalczysko@ls31619 ~/Work/omero-install]$ 
```

**Comment by sbesson** [comment]
```
sbesson@ls30630:2015-01 $ brew install omero
==> Installing omero from ome/homebrew-alt
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.openmicroscopy.org/omero/5.2.0/artifacts/openmi
######################################################################## 100.0%
==> ./build.py -Dice.home=/usr/local/opt/zeroc-ice35 build-default
...
```

I can't reproduce locally. COuld it be a connection issue?

**Comment by pwalczysko** [comment]
Connection issue - no, the failure is occuring whilst the connection is perfect, and it occurs very quickly.
Is of any importance that I have run the command twice, breaking it up the first time ?

**Comment by pwalczysko** [comment]
```
[pwalczysko@ls31619 /Library/Caches/Homebrew]$ brew install omero
==> Installing omero from ome/homebrew-alt
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.openmicroscopy.org/omero/5.2.0/artifacts/openmicroscopy-5.2.0.zip
######################################################################## 100.0%
==> ./build.py -Dice.home=/usr/local/opt/zeroc-ice35 build-default
Last 15 lines from /Users/pwalczysko/Library/Logs/Homebrew/omero/01.build.py:
        :: zeroc#ice-grid;3.5.1!ice-grid.jar
        :: zeroc#ice-db;3.5.1!ice-db.jar
        :: zeroc#ice-freeze;3.5.1!ice-freeze.jar
        ::::::::::::::::::::::::::::::::::::::::::::::


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/private/tmp/omero20151125-10883-jt2f5p/openmicroscopy-5.2.0/build.xml:178: The following error occurred while executing this line:
/private/tmp/omero20151125-10883-jt2f5p/openmicroscopy-5.2.0/components/antlib/resources/global.xml:430: The following error occurred while executing this line:
/private/tmp/omero20151125-10883-jt2f5p/openmicroscopy-5.2.0/components/antlib/resources/lifecycle.xml:67: impossible to resolve dependencies:
    resolve failed - see output for details

Total time: 93 minutes 23 seconds

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ome/homebrew-alt/issues

[pwalczysko@ls31619 /Library/Caches/Homebrew]$ 
```

**Comment by pwalczysko** [comment]
Running `brew update` and rerunning the `brew install omero` did not help. Switching off McAffee did not help either. Same error.

**Comment by dominikl** [comment]
I have a bit trouble building a OSX walkthrough doc with these scripts. Because there are two scripts, with mixed purpose: step01 for installing homebrew and python and step02 does all the rest (postgres, pyhton_deps, omero, etc.). Can we split this up into step01_requirements (homebrew, python, postgres, ...) and step02_omero (which really only install omero)?

**Comment by sbesson** [comment]
@dominikl: :+1: for splitting these steps as needed.

**Comment by pwalczysko** [comment]
Postgres is installed using scripts ? So the doc will be changed ?

screen shot 2015-11-27 at 16 17 11

**Comment by dominikl** [comment]
@pwalczysko 
Yes, currently `step02_omero.sh` also performs the postgres installation. For the doc it would be good to have all these requirement in one shell script, and all the omero installtion steps in another one, so we could have two sections "Prerequirements" and "Installing OMERO server", matching the Linux walkthrough: http://www.openmicroscopy.org/site/support/omero5.2-staging/sysadmins/unix/server-linux-walkthrough.html

**Pull request closed without merging**
