### PR TITLE
Debian10 support

### PR DESCRIPTION
**Pull request by jburel**
Run omero server on Debian 10

Installation tested via travis

Corresponding doc PR https://github.com/ome/ome-documentation/pull/2084

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good. Tested it with a debian10 VM, works well, omero-server running. Although I couldn't connect to it with Insight from the host machine, but that's probably some port forwarding or firewall issue.

**Comment by dominikl** [comment]
Well actually, there is something weird going on. Sudo'ed to `omero-server` user, wanted to run diagnostics:
```
omero-server@debian10:/opt/omero/server/OMERO.server/bin$ ./omero admin diagnostics
********************************************************************************

        ERROR: Could not import omero.cli! (No module named Ice)

        This means that your installation is incomplete. Contact
        the OME mailing lists for more information:

        https://www.openmicroscopy.org/support/

        If you are building from source, please supply the build log
        as well as which version you are building from. If you
        downloaded a distribution, please provide which link you
        used.

********************************************************************************

        Debugging Info:
        --------------
        CWD=/opt/omero/server/OMERO.server-5.6.0-m4-ice36-b128/bin
        VERSION=2.7.16 (default, Oct 10 2019, 22:02:15)  [GCC 8.3.0]
        OMERO_HOME=None
        PYTHONPATH=['/opt/omero/server/OMERO.server-5.6.0-m4-ice36-b128/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/opt/omero/server/OMERO.server-5.6.0-m4-ice36-b128/lib/python', '/opt/omero/server/OMERO.server-5.6.0-m4-ice36-b128/var/lib', '/opt/omero/server/OMERO.server-5.6.0-m4-ice36-b128/lib/fallback']
```

**Comment by jburel** [comment]
you will have to do:
``. /home/omero-server/settings.env omero ....`` to export variable like ``OMERODIR`` or ``PATH``

**Comment by dominikl** [comment]
Thanks. That works now. But can't login locally either:
```
omero-server@debian10:/opt/omero/server/OMERO.server/bin$ ./omero login
Server: [localhost:4064]
Username: [omero-server]root
Password:
WARNING:omero.client:..Ignoring error in client.__del__:<class 'Ice.SocketException'>
InternalException: Failed to connect: Ice.SocketException:
Cannot assign requested address
```
I'll try to run the install script again, this time carefully looking for errors in the output...

**Comment by jburel** [comment]
So far
* set `` omero config set Ice.IPv6 0``
* comment out line with ``ip6-*`` in ``/etc/hosts``
I can now run
 ``omero login -s 127.0.0.1 -p 4064 -u root -w omero_root_password`` and
``omero login -s localhost -p 4064 -u root -w omero_root_password``
and have the same error
```
WARNING:omero.client:..Ignoring error in client.__del__:<class 'Ice.ProtocolException'>
InternalException: Failed to connect: exception ::Ice::ProtocolException
{
    reason = SSL error occurred for new outgoing connection:
remote address = 127.0.0.1:4064
no protocols available
}
```

Downgrading openssl from ``1.1.1d`` to ``1.1.0f`` did not change anything

**Comment by jburel** [comment]
I managed to get the error without settings ``omero config set Ice.IPv6 0 `` but this time the config ``omero config set omero.glacier2.IceSSL.Ciphers HIGH:ADH:@SECLEVEL=0`` was not set

**Comment by jburel** [comment]
I have tried the various protocols supported by Ice
* ``SSL3`` -> ``IceSSL: OpenSSL was build without SSLv3 support``
* ``TLS1`` or ``TLS1_1`` -> ``no protocols available``
* ``TLS1_2`` -> ``tlsv1 alert internal error: SSL alert number 80``

running out of ideas

**Comment by dominikl** [comment]
I have the same issues with a debian VM installed from scratch (previously I was using vagrant). But I get another strange issue, when I run `omero admin diagnostics` I get `FileNotFoundError: [Errno 2] No such file or directory: 'icegridadmin': 'icegridadmin'`.

**Comment by mtbc** [comment]
Huh, did zeroc-ice-utils get installed?

**Comment by dominikl** [comment]
Apparently not... ah I had some `bdist_wheel` errors when running the install script. Maybe that's why? Still don't get it what this bdist_wheel stuff is.

**Comment by jburel** [comment]
ignore the ``bdist_wheel``
I do not have the error you indicated when running in docker

**Comment by dominikl** [comment]
No luck with a vanilla debian10 installation either. I also tried to install the ice stuff from zeroc directly, to rule out potential issues in https://github.com/ome/zeroc-ice-debian10 .
Then also tried to use the python lib from zeroc too via `pip install zeroc-ice=='3.6.5'`.
In either case I got the 
```
InternalException: Failed to connect: exception ::Ice::ProtocolException
{
    reason = SSL error occurred for new outgoing connection:
remote address = 127.0.0.1:4064
no protocols available
}
```
Whish one could get more details about the error...

Btw @mtbc was right, when I ran the omero install script `zeroc-ice-utils` was missing. After installing it manually I didn't get the error about the missing icegridadmin any longer.

**Comment by dominikl** [comment]
Good to merge now 👍 Tested again with an vanilla debian10 VM in virtualbox.

**Comment by joshmoore** [comment]
@jburel : did I understand correctly that you wouldn't merge this until the omeroweb-install PR is passing as well?

**Comment by jburel** [comment]
I think it is better to have both at the same time.
I think we should not include it in the 5.6 tag

**Comment by dominikl** [comment]
Makes sense. Btw, just followed the web installation docs for Ubuntu 18.04. Works fine, no problems. Just had to use the ice package for debian10 obviously.

**Comment by jburel** [comment]
Merging for 5.6

**Pull request merged**
