### PR TITLE
ubuntu ice 3.6 key

### PR DESCRIPTION
**Pull request by jburel**
Adjust key retrieval command

see https://github.com/ome/omero-install/issues/148
cc @heidricha

### CODE REVIEW

**Comment by jburel** [comment]
Travis is green
The installation works fine

**Comment by dominikl** [comment]
Looks alright, and works. I just wonder why my ubuntu1604 docker build yesterday worked, without this PR (when testing https://github.com/ome/omero-install/pull/146#issuecomment-288341734 ).

**Comment by jburel** [comment]
It was working with the previous command for our configuration

**Comment by dominikl** [comment]
Last commit works, too 👍

**Pull request merged**
