### PR TITLE
Centos 6 Python 2.7 SCL

### PR DESCRIPTION
**Pull request by manics**
Replaces #42. Added some scripts to sit alongside the existing ones for:
- Centos 6 Python 2.7 Nginx
- Centos 6 Python 2.7 Apache 2.4

I've also split the `install.sh` into separate files for each OS/webserver combination.

Todo:
- [ ] .travis.yml

### CODE REVIEW

**Comment by manics** [comment]
This should work once OMERO is fixed to generate an Apache 2.4 config file: https://github.com/manics/openmicroscopy/tree/apache24-wsgi

**Comment by joshmoore** [comment]
Reached the expected location:
```
Complete!
+ cp /home/omero/OMERO.server/apache.conf.tmp /opt/rh/httpd24/root/etc/httpd/conf.d/omero-web.conf
+ chkconfig httpd24-httpd on
+ service httpd24-httpd start
Starting httpd: AH00526: Syntax error on line 72 of /opt/rh/httpd24/root/etc/httpd/conf.d/omero-web.conf:
Either all Options must start with + or -, or no Option may.
[FAILED]
The command '/bin/sh -c cd omero-install-test && bash install-centos6py27-apache.sh' returned a non-zero code: 1
```

**Comment by joshmoore** [comment]
Merging then. @manics : thoughts on getting the apache PR opened so we can manually change the URL to use the merge build tomorrow?

**Comment by manics** [comment]
https://github.com/openmicroscopy/openmicroscopy/pull/4328

**Comment by jburel** [comment]
Reached the same location on centos6/py26 with apache2.4

**Pull request merged**
