### PR TITLE
Apache drop

### PR DESCRIPTION
**Pull request by jburel**
Remove apache from omero-install

To test:
 * Make sure that there is no ref to apache
 * travis should be green
 * generate the walkthrough (``i.e. bash autogenerate.sh``) and check that there is no mention of apache in the files

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-DEV-merge-homebrew#153](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/153/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/153/consoleText) for more details.
Possible conflicts:
  - PR #135 jburel 'Pg96 support'
    - linux/install_ubuntu1404_apache24.sh
    - linux/install_centos6_py27_apache24.sh
    - linux/test/centos6_py27_ius_apache24/run.sh
    - linux/test/centos6_py27_apache24/run.sh
    - linux/test/centos6_py27_ius_apache22/run.sh
    - linux/install_centos7_apache24.sh
    - linux/install_centos6_py27_ius_apache24.sh
    - linux/install_centos6_py27_ius_apache22.sh
    - linux/install_debian8_apache24.sh

**Comment by jburel** [comment]
conflict will be in the README, i will sort it out when this is merged

**Comment by manics** [comment]
Looks good to me. Diff of the autogenerated walkthroughs with/without this PR
`$ diff -ur old/ new/`
```diff
diff -ur old/walkthrough_centos6_py27.sh new/walkthrough_centos6_py27.sh
--- old/walkthrough_centos6_py27.sh	2017-02-16 10:02:53.000000000 +0000
+++ new/walkthrough_centos6_py27.sh	2017-02-16 10:01:45.000000000 +0000
@@ -133,7 +133,7 @@
 psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
 #end-step04
 
-#start-step05: As root, install a Web server: Nginx or Apache
+#start-step05: As root, install Nginx
 #start-nginx
 set +u
 source /opt/rh/python27/enable
@@ -161,31 +161,6 @@
 service nginx start
 #end-nginx
 
-#start-apache
-#start-copy
-cp setup_omero_apache24.sh ~omero
-#end-copy
-#start-configure-apache: As the omero system user, configure OMERO.web
-OMERO.server/bin/omero config set omero.web.application_server wsgi
-OMERO.server/bin/omero web config apache24 --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
-OMERO.server/bin/omero web syncmedia
-#end-configure-apache
-#start-apache-install
-set +u
-source /opt/rh/python27/enable
-set -u
-
-yum -y install httpd24-httpd python27-mod_wsgi
-
-# Install OMERO.web requirements
-pip install -r ~omero/OMERO.server/share/web/requirements-py27-apache.txt
-
-cp ~omero/OMERO.server/apache.conf.tmp /opt/rh/httpd24/root/etc/httpd/conf.d/omero-web.conf
-
-chkconfig httpd24-httpd on
-service httpd24-httpd start
-#end-apache-install
-#end-apache
 #end-step05
 
 #start-step06: As root, run the scripts to start OMERO and OMERO.web automatically
diff -ur old/walkthrough_centos6_py27_ius.sh new/walkthrough_centos6_py27_ius.sh
--- old/walkthrough_centos6_py27_ius.sh	2017-02-16 10:02:54.000000000 +0000
+++ new/walkthrough_centos6_py27_ius.sh	2017-02-16 10:01:46.000000000 +0000
@@ -153,7 +153,7 @@
 psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
 #end-step04
 
-#start-step05: As root, install a Web server: Nginx or Apache
+#start-step05: As root, install Nginx
 #start-nginx
 cat << EOF > /etc/yum.repos.d/nginx.repo
 [nginx]
@@ -184,45 +184,6 @@
 service nginx start
 #end-nginx
 
-#start-apache
-#start-copy
-cp setup_omero_apache22.sh ~omero
-#end-copy
-#start-configure-apache: As the omero system user, configure OMERO.web
-OMERO.server/bin/omero config set omero.web.application_server wsgi
-OMERO.server/bin/omero web config apache --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
-OMERO.server/bin/omero web syncmedia
-#end-configure-apache
-#start-apache-install
-#install Apache 2.2
-yum -y install httpd
-
-# install mod_wsgi compiled against 2.7
-yum -y install python27-mod_wsgi
-
-virtualenv -p /usr/bin/python2.7 /home/omero/omeroenv
-set +u
-source /home/omero/omeroenv/bin/activate
-set -u
-
-# Install OMERO.web requirements
-file=~omero/OMERO.server/share/web/requirements-py27-apache.txt
-# introduced in 5.2.0
-if [ -f $file ]; then
-	/home/omero/omeroenv/bin/pip2.7 install -r $file
-fi
-deactivate
-
-
-# Add virtual env python to the python-path parameter of the WSGIDaemonProcess directive
-sed -i 's/\(python-path\=\)/\1\/home\/omero\/omeroenv\/lib64\/python2.7\/site-packages:/' ~omero/OMERO.server/apache.conf.tmp
-
-cp ~omero/OMERO.server/apache.conf.tmp /etc/httpd/conf.d/omero-web.conf
-
-chkconfig httpd on
-service httpd start
-#end-apache-install
-#end-apache
 #end-step05
 
 #start-step06: As root, run the scripts to start OMERO and OMERO.web automatically
diff -ur old/walkthrough_centos7.sh new/walkthrough_centos7.sh
--- old/walkthrough_centos7.sh	2017-02-16 10:02:52.000000000 +0000
+++ new/walkthrough_centos7.sh	2017-02-16 10:01:44.000000000 +0000
@@ -97,7 +97,7 @@
 psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
 #end-step04
 
-#start-step05: As root, install a Web server: Nginx or Apache
+#start-step05: As root, install Nginx
 #start-nginx
 # The following is only required to install
 # latest stable version of nginx
@@ -128,41 +128,9 @@
 systemctl start nginx
 #end-nginx
 
-#start-apache
-#start-copy
-cp setup_omero_apache24.sh ~omero
-#end-copy
-#start-configure-apache: As the omero system user, configure OMERO.web
-OMERO.server/bin/omero config set omero.web.application_server wsgi
-OMERO.server/bin/omero web config apache24 --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
-OMERO.server/bin/omero web syncmedia
-#end-configure-apache
-#start-apache-install
-yum -y install httpd mod_wsgi
-
-# Install OMERO.web requirements
-pip install -r ~omero/OMERO.server/share/web/requirements-py27-apache.txt
-
-cp ~omero/OMERO.server/apache.conf.tmp /etc/httpd/conf.d/omero-web.conf
-
-rm -rf /run/httpd/* /tmp/httpd*
-
-systemctl enable httpd.service
-
-systemctl start httpd
-#end-apache-install
-#end-apache
 #end-step05
 
 #start-step06: As root, run the scripts to start OMERO and OMERO.web automatically
-cp omero-systemd.service /etc/systemd/system/omero.service
-
-cp omero-web-systemd.service /etc/systemd/system/omero-web.service
-
-systemctl daemon-reload
-
-systemctl enable omero.service
-systemctl enable omero-web.service
 #end-step06
 
 #start-step07: As root, secure OMERO
diff -ur old/walkthrough_debian8.sh new/walkthrough_debian8.sh
--- old/walkthrough_debian8.sh	2017-02-16 10:02:56.000000000 +0000
+++ new/walkthrough_debian8.sh	2017-02-16 10:01:47.000000000 +0000
@@ -86,7 +86,7 @@
 psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
 #end-step04
 
-#start-step05: As root, install a Web server: Nginx or Apache
+#start-step05: As root, install Nginx
 #start-nginx
 echo "deb http://nginx.org/packages/debian/ jessie nginx" >> /etc/apt/sources.list
 wget http://nginx.org/keys/nginx_signing.key
@@ -107,30 +107,6 @@
 service nginx start
 #end-nginx
 
-#start-apache
-#start-copy
-cp setup_omero_apache24.sh ~omero
-#end-copy
-#start-configure-apache: As the omero system user, configure OMERO.web
-OMERO.server/bin/omero config set omero.web.application_server wsgi
-OMERO.server/bin/omero web config apache24 --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
-OMERO.server/bin/omero web syncmedia
-#end-configure-apache
-#start-apache-install
-apt-get -y install apache2 libapache2-mod-wsgi
-
-# Install OMERO.web requirements
-pip install -r ~omero/OMERO.server/share/web/requirements-py27-apache.txt
-
-# Modify the default value set for the ``WSGISocketPrefix`` directive in ``apache.conf.tmp``
-sed -i -r -e 's|(WSGISocketPrefix run/wsgi)|#\1|' -e 's|# (WSGISocketPrefix /var/run/wsgi)|\1|' ~omero/OMERO.server/apache.conf.tmp
-cp ~omero/OMERO.server/apache.conf.tmp /etc/apache2/sites-available/omero-web.conf
-a2dissite 000-default.conf
-a2ensite omero-web.conf
-
-service apache2 start
-#end-apache-install
-#end-apache
 #end-step05
 
 #start-step06: As root, run the scripts to start OMERO and OMERO.web automatically
diff -ur old/walkthrough_ubuntu1404.sh new/walkthrough_ubuntu1404.sh
--- old/walkthrough_ubuntu1404.sh	2017-02-16 10:02:55.000000000 +0000
+++ new/walkthrough_ubuntu1404.sh	2017-02-16 10:01:47.000000000 +0000
@@ -95,7 +95,7 @@
 psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
 #end-step04
 
-#start-step05: As root, install a Web server: Nginx or Apache
+#start-step05: As root, install Nginx
 #start-nginx
 # require to install more recent version of nginx
 # w/o the version installed is 1.4.6
@@ -117,30 +117,6 @@
 service nginx start
 #end-nginx
 
-#start-apache
-#start-copy
-cp setup_omero_apache24.sh ~omero
-#end-copy
-#start-configure-apache: As the omero system user, configure OMERO.web
-OMERO.server/bin/omero config set omero.web.application_server wsgi
-OMERO.server/bin/omero web config apache24 --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
-OMERO.server/bin/omero web syncmedia
-#end-configure-apache
-#start-apache-install
-apt-get -y install apache2 libapache2-mod-wsgi
-
-# Install OMERO.web requirements
-pip install -r ~omero/OMERO.server/share/web/requirements-py27-apache.txt
-
-# Modify the default value set for the ``WSGISocketPrefix`` directive in ``apache.conf.tmp``
-sed -i -r -e 's|(WSGISocketPrefix run/wsgi)|#\1|' -e 's|# (WSGISocketPrefix /var/run/wsgi)|\1|' ~omero/OMERO.server/apache.conf.tmp
-cp ~omero/OMERO.server/apache.conf.tmp /etc/apache2/sites-available/omero-web.conf
-a2dissite 000-default.conf
-a2ensite omero-web.conf
-
-service apache2 start
-#end-apache-install
-#end-apache
 #end-step05
 
 #start-step06: As root, run the scripts to start OMERO and OMERO.web automatically
diff -ur old/walkthrough_ubuntu1604.sh new/walkthrough_ubuntu1604.sh
--- old/walkthrough_ubuntu1604.sh	2017-02-16 10:02:57.000000000 +0000
+++ new/walkthrough_ubuntu1604.sh	2017-02-16 10:01:48.000000000 +0000
@@ -92,7 +92,7 @@
 psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
 #end-step04
 
-#start-step05: As root, install a Web server: Nginx or Apache
+#start-step05: As root, install Nginx
 #start-nginx
 # require to install more recent version of nginx
 # w/o the version installed is 1.4.6
@@ -114,30 +114,6 @@
 service nginx start
 #end-nginx
 
-#start-apache
-#start-copy
-cp setup_omero_apache24.sh ~omero
-#end-copy
-#start-configure-apache: As the omero system user, configure OMERO.web
-OMERO.server/bin/omero config set omero.web.application_server wsgi
-OMERO.server/bin/omero web config apache24 --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
-OMERO.server/bin/omero web syncmedia
-#end-configure-apache
-#start-apache-install
-apt-get -y install apache2 libapache2-mod-wsgi
-
-# Install OMERO.web requirements
-pip install -r ~omero/OMERO.server/share/web/requirements-py27-apache.txt
-
-# Modify the default value set for the ``WSGISocketPrefix`` directive in ``apache.conf.tmp``
-sed -i -r -e 's|(WSGISocketPrefix run/wsgi)|#\1|' -e 's|# (WSGISocketPrefix /var/run/wsgi)|\1|' ~omero/OMERO.server/apache.conf.tmp
-cp ~omero/OMERO.server/apache.conf.tmp /etc/apache2/sites-available/omero-web.conf
-a2dissite 000-default.conf
-a2ensite omero-web.conf
-
-service apache2 start
-#end-apache-install
-#end-apache
 #end-step05
 
 #start-step06: As root, run the scripts to start OMERO and OMERO.web automatically
```

**Comment by jburel** [comment]
Thanks merging

**Pull request merged**
