### PR TITLE
Pg96 support

### PR DESCRIPTION
**Pull request by jburel**
This PR adds support for postgresql 9.6

see https://trello.com/c/pqPzTMPY/235-omero-may-break-with-postgresql-9-6

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-DEV-merge-homebrew#138](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/138/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/138/consoleText) for more details.
Possible conflicts:
  - PR #134 jburel 'Java9'
    - .travis.yml

**Comment by jburel** [comment]
Started devspace to run pg 9.6 and 9.5

**Comment by jburel** [comment]
https://travis-ci.org/ome/omero-install/builds/202625492 build tested the installation of pg 9.6

**Comment by jburel** [comment]
see https://github.com/openmicroscopy/ome-documentation/pull/1619 for discussion

**Comment by jburel** [comment]
See c77140a

**Comment by joshmoore** [comment]
```
+ yum -y install http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-3.noarch.rpm
+ yum -y install http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-3.noarch.rpm
...
```

Is this being built anywhere? All the versions I see on travis are 9.4, correct?

**Comment by jburel** [comment]
On travis it is 9.4. I can push again a tmp commit to build 9.6 
This build https://github.com/ome/omero-install/pull/135#issuecomment-280663775
installed 9.6

**Comment by jburel** [comment]
9.5 and 9.6 testing have also been done in devspace 
cf. https://trello.com/c/pqPzTMPY/235-omero-may-break-with-postgresql-9-6
I have removed the images to free some space

**Comment by joshmoore** [comment]
I'm concerned that the "recommended" version isn't being run on travis, but we can follow-up on that before release.

**Pull request merged**
