### PR TITLE
Work-around to fix issue with systemd

### PR DESCRIPTION
**Pull request by jburel**
Fix issue noticed while testing figure on centos7 https://github.com/ome/omero-install/pull/71

### CODE REVIEW

**Comment by joshmoore** [comment]
cc @kennethgillen @manics especially since something like could have wider repercussions on production systems.

**Comment by manics** [comment]
What's the error you're trying to fix? A standard centos7 installation (VM, physical) and the docker image should already have the correct versions of systemd installed by default.

**Comment by jburel** [comment]
around ~100 lines like the following

```
file /usr/lib64/libsystemd-daemon.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-id128.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-journal.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-login.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libudev.so.1 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64

```

That's a new error. It was working fine over the weekend when I worked on figure.

**Comment by kennethgillen** [comment]
@joshmoore @manics @jburel: Since the error is re: `systemd-container`, it's unlikely to hit a non-docker system. I wouldn't expect many people to hit this in the wild, but maybe my expectation of the wild != docker deployments is wrong..

**Comment by manics** [comment]
> `file /usr/lib64/libsystemd-daemon.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64`

Sounds like your docker container is out of date. `docker pull centos`/`docker pull centos:centos7`?

**Comment by jburel** [comment]
same issue.
reading https://hub.docker.com/_/centos/, we may want to change the base image `omero-ssh-systemd` in `https://github.com/ome/ome-docker`

**Comment by kennethgillen** [comment]
@manics: concur: updated the docker container, same issue.

> file /usr/share/zsh/site-functions/_udevadm from install of systemd-219-19.el7.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64

**Comment by manics** [comment]
OK, `ome-docker/omero-ssh-systemd` which builds on `centos:7` needs to be rebuilt

**Comment by manics** [comment]
Actually, it looks like it was already rebuilt yesterday. `docker pull openmicroscopy/omero-ssh-systemd`?

**Comment by jburel** [comment]
No difference

**Comment by jburel** [comment]
```
 docker pull openmicroscopy/omero-ssh-systemd
Using default tag: latest
latest: Pulling from openmicroscopy/omero-ssh-systemd
Digest: sha256:a3b957ecd2d9174bb815013c79611e577f66de5714c8d0dfe8ed576f37de9dba
Status: Image is up to date for openmicroscopy/omero-ssh-systemd:latest
```
same error

**Comment by manics** [comment]
```
$ docker pull openmicroscopy/omero-ssh-systemd
latest: Pulling from docker.io/openmicroscopy/omero-ssh-systemd
47d44cb6f252: Already exists
168a69b62202: Already exists
812e9d9d677f: Already exists
4234bfdd88f8: Already exists
ce20c473cd8a: Already exists
19385dfab3ba: Already exists
03c5276b5a45: Already exists
ed35252dcfd7: Already exists
ca3e9b0ce671: Already exists
b4640b4b34da: Already exists
8fe8db66a60d: Already exists
5b02a060b830: Already exists
8f0cc83fb917: Already exists
Digest: sha256:a3b957ecd2d9174bb815013c79611e577f66de5714c8d0dfe8ed576f37de9dba
Status: Image is up to date for docker.io/openmicroscopy/omero-ssh-systemd:latest
$ docker run -it --entrypoint bash --rm openmicroscopy/omero-ssh-systemd
[root@3e960b941942 /]# rpm -qa systemd\*
systemd-container-libs-208.20-6.el7.centos.x86_64
systemd-container-208.20-6.el7.centos.x86_64
[root@3e960b941942 /]# exit
exit
```

**Comment by manics** [comment]
```
$ docker images docker.io/openmicroscopy/omero-ssh-systemd
REPOSITORY                                   TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker.io/openmicroscopy/omero-ssh-systemd   latest              8f0cc83fb917        25 hours ago        194.2 MB
```

**Comment by manics** [comment]
Confirmed by http://seven.centos.org/2015/12/fixing-centos-7-systemd-conflicts-with-docker/

This workaround isn't necessary, `docker pull` should fix it.

**Comment by jburel** [comment]
@manics: thanks for following that up
I will look at that post release

**Pull request closed without merging**
