### PR TITLE
Use omero-certificates

### PR DESCRIPTION
**Pull request by jburel**
install and configure omero-certificates

### CODE REVIEW

**Comment by joshmoore** [comment]
The related section is no longer "patching OMERO.server":

Screen Shot 2020-05-06 at 13 33 01

**Comment by jburel** [comment]
I have not really worked on the doc only re-use the file used to "patch", that's why it shows up like this

**Comment by joshmoore** [comment]
> I have not really worked on the doc only re-use the file used to "patch", that's why it shows up like this

Understood, but then two two should probably be merged together, no?

**Comment by jburel** [comment]
They are merged together, I have not looked at the text on the doc front.
What is coming from omero-install is only ``omero certificates`` the text around is in the doc

**Comment by dominikl** [comment]
Looks good to me 👍

**Comment by jburel** [comment]
Thanks @dominikl

**Pull request merged**
