### PR TITLE
Fix nginx Web config target for OMERO 5.2.x

### PR DESCRIPTION
**Pull request by sbesson**
Spotted while reviewing the auto-generation PR, see also https://github.com/ome/omero-install/pull/37#issuecomment-151295246

### CODE REVIEW

**Comment by joshmoore** [comment]
Testing gh-37, I just got:

```
omero-install/linux/test$ ./docker-build.sh centos6-apache
...
+ OMERO.server/bin/omero config set omero.web.application_server wsgi
+ OMERO.server/bin/omero web config apache --http 80
ERROR: configuration mismatch. omero.web.application_server=wsgi cannot be used with 'omero web config apache'.
The command '/bin/sh -c cd omero-install-test && bash install.sh centos6 apache' returned a non-zero code: 168
```

Related? cc: @manics

**Comment by sbesson** [comment]
Which server is that using? This is the same logic than the one used for the autogeneration scripts in https://github.com/openmicroscopy/ome-documentation/blob/develop/omero/autogen_docs#L36

**Comment by manics** [comment]
@joshmoore probably beacuse setup_omero./sh is still using the latest 5.1 release? Try jusing omerodev.sh instead.

**Comment by manics** [comment]
Thanks @sbesson

**Pull request merged**
