### PR TITLE
travis centos6

### PR DESCRIPTION
**Pull request by jburel**
Removing centos6-py27 from travis

### CODE REVIEW

**Comment by joshmoore** [comment]
Sorry, I missed the discussion. Why are these being removed?

**Comment by jburel** [comment]
Do we still need them to be built since it has been removed from our docs?

**Comment by joshmoore** [comment]
I'd suggest we either build them regularly or delete them.

**Comment by jburel** [comment]
No decision yet. We wait to have everybody back. Probably a discussion for the new year.Closing for now

**Comment by jburel** [comment]
If we keep them around, probably a good idea to provide a ice bundle built against SCL python
I will prepare one when we are done with 5.2.1

**Pull request closed without merging**
