### PR TITLE
Ubuntu apache start web

### PR DESCRIPTION
**Pull request by jburel**
To test: 
- in the `test` directory: run `./docker-build.sh ubuntu1404_apache24/`
- when done run `docker run -it -p 2222:22 -p 4063:4063 -p 4064:4064 -p 8080:80 omero_install_test_ubuntu1404_apache24`
  - Check that web is running

### CODE REVIEW

**Comment by dominikl** [comment]
Works fine, good to merge.

**Comment by manics** [comment]
Shouldn't this work without starting OMERO.web since it's using an Apache wsgi socket?

**Comment by joshmoore** [comment]
also "This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log." -- relaunched.

**Comment by jburel** [comment]
Closing. no need to have that change in

**Pull request closed without merging**
