### PR TITLE
Create link.

### PR DESCRIPTION
**Pull request by jburel**
Fix link when using ice 3.6
This PR does not need to merge immediately since we will need to point to the release url when ready.

### CODE REVIEW

**Comment by jburel** [comment]
I have re-organised a bit the walkthrough following comment on https://github.com/openmicroscopy/ome-documentation/pull/1451
This will have to be merged to take effect

**Comment by atarkowska** [comment]
I have just been testing ice 36 regarding https://github.com/ome/omero-install/pull/105 and

```
+ '[' ice36 = ice36 ']'
+ cd /home/omero
+ SERVER=https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-build/ICE=3.6,jdk=8_LATEST,label=octopus/lastSuccessfulBuild/artifact/src/target/OMERO.server-5.2.2-393-e464f65-ice36-b292.zip
+ wget https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-build/ICE=3.6,jdk=8_LATEST,label=octopus/lastSuccessfulBuild/artifact/src/target/OMERO.server-5.2.2-393-e464f65-ice36-b292.zip
--2016-04-27 19:05:30--  https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-build/ICE=3.6,jdk=8_LATEST,label=octopus/lastSuccessfulBuild/artifact/src/target/OMERO.server-5.2.2-393-e464f65-ice36-b292.zip
Resolving ci.openmicroscopy.org (ci.openmicroscopy.org)... 134.36.65.245
Connecting to ci.openmicroscopy.org (ci.openmicroscopy.org)|134.36.65.245|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-27 19:05:30 ERROR 404: Not Found.
```

artifacts are deleted daily right?

**Comment by jburel** [comment]
@aleksandra-tarkowska:
This link will have to be modified for the release.
it is tmp. To use it you will have to edit the file, and change it with a more recent one.

**Comment by jburel** [comment]
This PR has been merged so we can prepare the doc.
Another one will be opened when the release build is available

**Pull request merged**
