### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by joshmoore**
Attempt to have the repo green for tomorrow. The caching changes were to speed up local building.

### CODE REVIEW

**Comment by manics** [comment]
If it's easier you can set `OMEROVER=omerodev` in `install-centos6py27*.sh` to use `omego`, and if necessary change the branch in `setup_omerodev_centos6py27.sh`

**Comment by joshmoore** [comment]
Didn't manage to get this green for this morning. Closing and each can handle individually.

**Comment by manics** [comment]
If you decide to reopen this it'll conflict with #44 https://github.com/manics/omero-install/commit/36df6bd6137c3271fd9d1ed295538575424f34db

**Comment by joshmoore** [comment]
Thanks for the heads up, but I won't.

**Pull request closed without merging**
