### PR TITLE
omero.web python 2.7 only

### PR DESCRIPTION
**Pull request by atarkowska**
following https://github.com/openmicroscopy/openmicroscopy/pull/4783

### CODE REVIEW

**Comment by jburel** [comment]
fix autogen in https://github.com/aleksandra-tarkowska/omero-install/pull/3

**Comment by atarkowska** [comment]
thx @jburel for autogen update

**Comment by jburel** [comment]
Second round https://github.com/aleksandra-tarkowska/omero-install/pull/4

**Comment by jburel** [comment]
I think we are done  now.

**Comment by joshmoore** [comment]
Can the description here be updated to explain some of the changes:
- why the collapsing of the 3 web versions (nginx, apache22, apache24)?
- what is the purpose of `ALL=false`?

Or alternatively, an update to the README? It still contains:

```
bash install_centos6_apache22.sh
bash install_centos6_nginx.sh
```

**Comment by jburel** [comment]
I introduced that at the time of the latest release (a bit under pressure!) to generate all the walkthroughs  for the autogen (documentation side). If set to false, one can only generate the walkthrough he/she wants e.g. ubuntu1404, this is useful when updating the script.  We could certainly simplify.
It has nothing to do with this PR.

**Comment by jburel** [comment]
Note that the doc will be moved to the community repo as discussed last week.

**Comment by atarkowska** [comment]
see coming changes https://github.com/aleksandra-tarkowska/omeroweb-install

**Comment by joshmoore** [comment]
@jburel : shall we consider this ON_HOLD until we've made a decision on the Trial?

**Comment by jburel** [comment]
This is part of the "same package" so I think it should be on_hold until a decision is made.

**Comment by atarkowska** [comment]
Hmm how then we tag m4? I think this PR is not related to omeroweb-install and all the other PRs are already merged.

**Comment by atarkowska** [comment]
This PR is related to https://github.com/openmicroscopy/openmicroscopy/pull/4783

Trial PR https://github.com/openmicroscopy/openmicroscopy/pull/4805 is build on Breaking and tested via omeroweb-install (these 2 can be treated as a next step)

See the diff between them.

For me this should go in. Trial may still be on breaking and can be as part of m5, unless I misunderstood?

**Comment by joshmoore** [comment]
Ah, I think I understand.  Biggest remaining issue here then is the fact that _if_ we decide to not deprecate Apache, we may have to come back to this PR, correct?

**Comment by atarkowska** [comment]
how apache is related? this PR doped python 2.6 from web deployment for both nginx and apache

**Comment by joshmoore** [comment]
What does it mean then that:

```
 -  - ENV=centos6_nginx
 -  - ENV=centos6_apache22
```

become

```
 +  - ENV=centos6
```

?

**Comment by atarkowska** [comment]
it means that on centos6 scripts only install OMERO.server, no web deployment.

**Comment by joshmoore** [comment]
Ah, slowly I'm understanding. (Note: I _did_ say I was confused -- https://github.com/ome/omero-install/pull/114#issuecomment-241654240 :smile:)

**Comment by atarkowska** [comment]
np, that's why I am saying that PR is not related to TRIAL, is only a consequence of https://github.com/openmicroscopy/openmicroscopy/pull/4783

**Comment by joshmoore** [comment]
I agree now. It just seemed like this went along with the deprecation of apache. @jburel ?

**Comment by jburel** [comment]
By "full package" I mean the deprecation of python and the trial.
With the 5.2.6 coming: deprecation of apache, we can move forward with this PR.
I think Trial could become more "official" during the rest of the 5.3.0 work (i.e. remove trial!)
Happy to have that merged

**Comment by joshmoore** [comment]
Thanks, all.

**Comment by atarkowska** [comment]
thx for all the work

**Pull request merged**
