### PR TITLE
Selinux

### PR DESCRIPTION
**Pull request by jburel**
Update script used.

### CODE REVIEW

**Comment by joshmoore** [comment]
The changes make sense, but searching it looks like 2 of these files aren't referenced anywhere:

```
/opt/omero-install $ git grep docker_ | grep -v shutdown
linux/test/README.md:        bash docker_virtualenv_ius_apache24.sh
```

Worth trying to get these into a testing situation?

**Comment by jburel** [comment]
They should have already been tested when used in the  "centos6 scl python" context

**Comment by joshmoore** [comment]
I meant more of a regular, per-commit testing, i.e. our safety net so nothing slips into this repo.

**Comment by jburel** [comment]
I am planning to review those files post release.
This PR can wait now none of the files will be included in the doc
but if most of installation is done while running docker we will be in the same situation that we are with centos 7 i.e. not in travis

**Comment by jburel** [comment]
closing this PR since I am in the process of reviewing the files.

**Pull request closed without merging**
