### PR TITLE
add python-yaml and jinja2

### PR DESCRIPTION
**Pull request by atarkowska**
Add `python-yaml`, see
- https://github.com/openmicroscopy/openmicroscopy/pull/4880#pullrequestreview-4368666
- https://github.com/openmicroscopy/openmicroscopy/pull/4896

To test:

check if travis installed python-yaml in every case we test.

cc @jburel

### CODE REVIEW

**Comment by atarkowska** [comment]
Could someone restart failing debian test, please.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-DEV-merge-homebrew#61](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/61/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/61/consoleText) for more details.
Possible conflicts:
- PR #118 aleksandra-tarkowska 'test apache deprecation warning'
  - linux/step01_ubuntu1404_deps.sh

**Comment by manics** [comment]
I've lost track, is Centos 6 still supported by OMERO 5.3?

**Comment by atarkowska** [comment]
@manics https://trello.com/c/FXt1rXQl/1-scoping-team-req#comment-57eceb4d675da49855caddfd

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : will the installation documentation have a line/location saying, "yaml and jinja2 are required"?

**Comment by joshmoore** [comment]
Discussion on required vs. recommended:

 * Simon: If required, then e.g. `render.py` will fail; if recommended, then it should just not be operable
 * Josh: would bubble up recommended packages to the official documentation
 * Simon: if it's easy to install, then can see making it completely recommended

**Comment by joshmoore** [comment]
Merging. This means these will start showing up in the 5.3 documentation. We'll need to make sure that the representation of recommended v. required is clear. cc: @hflynn

**Comment by hflynn** [comment]
I'll reference this PR on the card for the installation docs

**Pull request merged**
