### PR TITLE
Remove 5.0, Switch to WSGI for web, add django

### PR DESCRIPTION
**Pull request by manics**
Switch all web servers to WSGI.
Also added an ~~omero51-merge~~omerodev script (which comes in useful for testing pre-release changes).

Ideally test this after http://downloads.openmicroscopy.org/latest/omero5.1/server-ice35.zip is updated to 5.1.4 (though in theory it should also work with 5.1.3 since WSGI support is included).

Updated: I've also changed the default install to use the `latest/omero5` redirect instead of `5.x`.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-homebrew/ICE=3.5,OSX=snapper#240](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.5,OSX=snapper/240/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.5,OSX=snapper/240/consoleText) for more details.
Possible conflicts:
  - PR #33 manics 'Use exec bash at end of docker test run.sh scripts'
    - linux/test/centos6-apache/run.sh

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-homebrew/ICE=3.4,OSX=snapper#240](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.4,OSX=snapper/240/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.4,OSX=snapper/240/consoleText) for more details.
Possible conflicts:
  - PR #33 manics 'Use exec bash at end of docker test run.sh scripts'
    - linux/test/centos6-apache/run.sh

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-homebrew/ICE=3.5,OSX=snapper#241](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.5,OSX=snapper/241/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.5,OSX=snapper/241/consoleText) for more details.
Possible conflicts:
  - PR #33 manics 'Use exec bash at end of docker test run.sh scripts'
    - linux/test/centos6-apache/run.sh

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-homebrew/ICE=3.4,OSX=snapper#241](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.4,OSX=snapper/241/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.4,OSX=snapper/241/consoleText) for more details.
Possible conflicts:
  - PR #33 manics 'Use exec bash at end of docker test run.sh scripts'
    - linux/test/centos6-apache/run.sh

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-cpp-5.1-merge-homebrew#83](https://ci.openmicroscopy.org/job/BIOFORMATS-cpp-5.1-merge-homebrew/83/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-cpp-5.1-merge-homebrew/83/consoleText) for more details.
Possible conflicts:
  - PR #33 manics 'Use exec bash at end of docker test run.sh scripts'
    - linux/test/centos6-apache/run.sh

**Comment by joshmoore** [comment]
Note: testing this currently with the following patch in order to work on https://github.com/openmicroscopy/openmicroscopy/pull/4294

```
diff --git a/linux/install.sh b/linux/install.sh
index 5625157..0ea33f1 100644
--- a/linux/install.sh
+++ b/linux/install.sh
@@ -4,7 +4,7 @@ set -e -u -x
 
 DISTRO=
 WEBSERVER=nginx
-OMEROVER=omero51
+OMEROVER=omero51-merge
 
 for arg in "$@"; do
 	case "$arg" in
diff --git a/linux/setup_omero51-merge.sh b/linux/setup_omero51-merge.sh
index 7868791..20a05ec 100644
--- a/linux/setup_omero51-merge.sh
+++ b/linux/setup_omero51-merge.sh
@@ -7,7 +7,7 @@ source settings.env
 virtualenv omego
 omego/bin/pip install omego
 
-BRANCH=OMERO-5.1-merge-build
+BRANCH=OMERO-DEV-merge-build
 
 omego/bin/omego download --branch $BRANCH server
 ln -s OMERO.server-*/ OMERO.server

```

**Comment by joshmoore** [comment]
Plus
```
-OMERO.server/bin/omero web config nginx-wsgi --http "$OMERO_WEB_PORT" > OMERO.server/nginx.conf.tmp
+OMERO.server/bin/omero web config nginx --http "$OMERO_WEB_PORT" > OMERO.server/nginx.conf.tmp
```

**Comment by joshmoore** [comment]
Few more changes. Here's the full patch needed (though in the wrong file!):

```
diff --git a/linux/install.sh b/linux/install.sh
index 5625157..0ea33f1 100644
--- a/linux/install.sh
+++ b/linux/install.sh
@@ -4,7 +4,7 @@ set -e -u -x
 
 DISTRO=
 WEBSERVER=nginx
-OMEROVER=omero51
+OMEROVER=omero51-merge
 
 for arg in "$@"; do
 	case "$arg" in
diff --git a/linux/setup_omero51-merge.sh b/linux/setup_omero51-merge.sh
index 7868791..6e18606 100644
--- a/linux/setup_omero51-merge.sh
+++ b/linux/setup_omero51-merge.sh
@@ -4,14 +4,19 @@ set -e -u -x
 
 source settings.env
 
-virtualenv omego
-omego/bin/pip install omego
+virtualenv --system-site-packages omego
+set +o nounset
+. omego/bin/activate
+set -o nounset
 
-BRANCH=OMERO-5.1-merge-build
+pip install omego
 
-omego/bin/omego download --branch $BRANCH server
+BRANCH=OMERO-DEV-merge-build
+
+omego download --branch $BRANCH server
 ln -s OMERO.server-*/ OMERO.server
 
+pip install -r OMERO.server/share/web/requirements-py26.txt
 OMERO.server/bin/omero config set omero.data.dir "$OMERO_DATA_DIR"
 OMERO.server/bin/omero config set omero.db.name "$OMERO_DB_NAME"
 OMERO.server/bin/omero config set omero.db.user "$OMERO_DB_USER"
@@ -21,4 +26,4 @@ OMERO.server/bin/omero db script -f OMERO.server/db.sql --password "$OMERO_ROOT_
 psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
 
 OMERO.server/bin/omero config set omero.web.application_server wsgi-tcp
-OMERO.server/bin/omero web config nginx-wsgi --http "$OMERO_WEB_PORT" > OMERO.server/nginx.conf.tmp
+OMERO.server/bin/omero web config nginx --http "$OMERO_WEB_PORT" > OMERO.server/nginx.conf.tmp
```

**Comment by joshmoore** [comment]
And Apache:

```
diff --git a/linux/setup_omero_apache.sh b/linux/setup_omero_apache.sh
index 3ad8201..9276f68 100644
--- a/linux/setup_omero_apache.sh
+++ b/linux/setup_omero_apache.sh
@@ -4,6 +4,10 @@ set -e -u -x
 
 source settings.env
 
+set +o nounset
+. omego/bin/activate
+set -o nounset
+
 OMERO.server/bin/omero config set omero.web.application_server wsgi
-OMERO.server/bin/omero web config apache-wsgi --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
+OMERO.server/bin/omero web config apache --http "$OMERO_WEB_PORT" > OMERO.server/apache.conf.tmp
 OMERO.server/bin/omero web syncmedia

```

**Comment by manics** [comment]
I've tried to prevent the number of combinations from growing, so:
- renamed `omero51` to `omero` (will always be the recommended version of OMERO)
- `omero-merge` to `omerodev` (`OMERO-DEV-latest`)

`omero config web nginx ...` is changed, however the build will fail due to a hard requirement on gunicorn which is currently installed later in the process https://trello.com/c/07pqxE0t/100-omero-web-config-nginx-should-warn-but-not-fail

```
-virtualenv omego
-omego/bin/pip install omego
+virtualenv --system-site-packages omego
+set +o nounset
+. omego/bin/activate
+set -o nounset

-BRANCH=OMERO-5.1-merge-build
+pip install omego

-omego/bin/omego download --branch $BRANCH server
+BRANCH=OMERO-DEV-merge-build
+
+omego download --branch $BRANCH server
 ln -s OMERO.server-*/ OMERO.server

+pip install -r OMERO.server/share/web/requirements-py26.txt
```
I guess this is because you want to reuse the virtualenv? It'll require changes to the init.d scripts, so I think it'd be better to install non-omego requirements into the system pip instead.

**Comment by manics** [comment]
I'll come back to this after the `web config` stuff is sorted.

**Comment by manics** [comment]
I think that's it. Note this won't work until `latest/omero5` points to `5.2.0`

**Comment by manics** [comment]
OK, this really is it (I think). Since I forgot to remove the `OMERO.server/bin/omero config set omero.web.application_server wsgi-tcp` line (which isn't necessary because it's the default in 5.2) this worka with 5.1.4 nginx anyway, and we don't publish the apache walkthoughs in our main sysadmin docs.

**Comment by sbesson** [comment]
@manics: I realize the file renaming will conflict with the autogeneration script in OMERO. Only unresolved issue from @joshmoore is the `web config nginx-wgsi - > web config nginx` in OMERO 5.2. I propose we merge this PR as it is and work through amendments in follow-up PRs as well as the inclusion in the Sphinx documentation which will require additional work.

**Comment by joshmoore** [comment]
Merging to allow the docs to be updated. I'll continue testing locally (via docker) and we can open a bug fixing PR as needed.

**Pull request merged**
