### PR TITLE
use individual packages instead of meta-package

### PR DESCRIPTION
**Pull request by jburel**
use individual packages instead of meta-package
cc @sbesson 

Check that travis is green

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Matches the changes discussed and merged in https://github.com/ome/ansible-role-ice/pull/14. Travis is successfully testing all combinations. I would have expected https://github.com/ome/omero-install/blob/develop/linux/test/test_services.sh#L45 would print the Java version used in the various combinations but it looks like the output is lost. Is there a simple way to enable it?

Otherwise, LGTM

**Comment by joshmoore** [comment]
Ditto. Do we know if this resulted in the wrong JDK installed anywhere? i.e. do we need to add a warning of any kind?

**Comment by manics** [comment]
`su - test -c '. /etc/profile.d/less.sh sad asd asjhdsakjhfadkslhf'`
This sources the first file but doesn't actually run the command.....

**Comment by jburel** [comment]
this is test code introduced by Ola a while ago. I will need to get back to it

**Comment by sbesson** [comment]
https://github.com/sbesson/omero-install/commit/f43713388e3cf50e933b19378428f81f6cba205d should do the first bit i.e. allow `docker exec` output to be printed. 
As Simon says, the diagnostics and login command are not executed.

**Comment by jburel** [comment]
The command is now run.
Java 1.8 is set since JAVAVER was set to openjdk1.8
```
docker exec -it omeroinstall_centos7 /bin/bash -c 'su - omero-server -c ". /home/omero-server/settings.env && omero admin diagnostics"'
================================================================================
OMERO Diagnostics (admin) 5.7.1
================================================================================
        
Commands:   java -version                  1.8.0     (/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/bin/icegridadmin)
Commands:   psql --version                 10.14     (/bin/psql)
Commands:   openssl version                not found
Server:     icegridnode                    running
Server:     Blitz-0                        active (pid = 608, enabled)
Server:     DropBox                        inactive (disabled)
Server:     FileServer                     inactive (disabled)
Server:     Indexer-0                      active (pid = 630, enabled)
Server:     MonitorServer                  inactive (disabled)
Server:     OMERO.Glacier2                 active (pid = 644, enabled)
Server:     OMERO.IceStorm                 active (pid = 646, enabled)
Server:     PixelData-0                    active (pid = 654, enabled)
Server:     Processor-0                    active (pid = 667, enabled)
Server:     Tables-0                       active (pid = 679, enabled)
Server:     TestDropBox                    inactive (enabled)
```

**Comment by joshmoore** [comment]
Ok, so I understand that in the case of omero-install we were always on JDK8 and _wanted_ to be but had we _tried_ to go to JDK11 we would have had the same problem, right? If so, :+1:

**Comment by jburel** [comment]
The recommended version in our doc is Java 11. so this is the output when the recommended version is used.

```
+docker exec -it omeroinstall_centos7 /bin/bash -c 'su - omero-server -c ". /home/omero-server/settings.env && omero admin diagnostics"'
================================================================================
OMERO Diagnostics (admin) 5.7.1
================================================================================
        
Commands:   java -version                  11.0.8    (/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/bin/icegridadmin)
Commands:   psql --version                 11.9      (/bin/psql)
Commands:   openssl version                not found

```

**Comment by sbesson** [comment]
The output of the various CentOS7 combinations now produce the expected result - see https://travis-ci.org/github/ome/omero-install/jobs/725545336

```
+docker exec -it omeroinstall_centos7 /bin/bash -c 'su - omero-server -c ". /home/omero-server/settings.env && omero admin diagnostics"'
================================================================================
OMERO Diagnostics (admin) 5.7.1
================================================================================
        
Commands:   java -version                  1.8.0     (/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/bin/icegridadmin)
Commands:   psql --version                 10.14     (/bin/psql)
Commands:   openssl version                not found
```

vs https://travis-ci.org/github/ome/omero-install/jobs/725545344

```
+docker exec -it omeroinstall_centos7 /bin/bash -c 'su - omero-server -c ". /home/omero-server/settings.env && omero admin diagnostics"'

================================================================================
OMERO Diagnostics (admin) 5.7.1
================================================================================
        
Commands:   java -version                  11.0.8    (/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/bin/icegridadmin)
Commands:   psql --version                 11.9      (/bin/psql)
Commands:   openssl version                not found
```

Ubuntu 20.04 and CentOS8 are now failing when executing the login command. Should we move these to expected failing builds and investigate separately?

**Comment by jburel** [comment]
I am now running to a test without the commit to be sure that Java 1.8 was always used with the meta-package. I will paste the output when it is done

**Comment by jburel** [comment]
Built with Java 11 and the meta package
https://travis-ci.org/github/jburel/omero-install/jobs/725549431
```
+docker exec -it omeroinstall_centos7 /bin/bash -c 'su - omero-server -c ". /home/omero-server/settings.env && omero admin diagnostics"'
================================================================================
OMERO Diagnostics (admin) 5.7.1
================================================================================
        
Commands:   java -version                  1.8.0     (/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/bin/icegridadmin)
Commands:   psql --version                 11.9      (/bin/psql)
Commands:   openssl version                not found
```
So with this PR we now get the correct Java version used

**Comment by jburel** [comment]
The 2 failures should be investigated in a separate PR

**Comment by sbesson** [comment]
> The 2 failures should be investigated in a separate PR

Works for me. Can you mark them as `allowed_failures` so that we don't block other contributions if we don't get back to them in the meantime?

**Comment by jburel** [comment]
I was checking if I could find a quick solution.
I have built the docker image locally for Ubuntu2004, started the server and logged in without problem :-)

**Pull request merged**
