### PR TITLE
Remove plpgsql comment

### PR DESCRIPTION
**Pull request by manics**
Comment is now out of date since we don't support 8.4

### CODE REVIEW

**Comment by mtbc** [comment]
Well-spotted. Good to merge. :+1:

(I wonder if we have any remaining CREATELANG elsewhere in our docs.)

**Comment by mtbc** [comment]
(Yeah, three in `omero/sysadmins/unix/` -- you want to do them or shall I?)

**Comment by manics** [comment]
Should be in https://github.com/openmicroscopy/ome-documentation/pull/1157 24d7bdc (though feel free to check)

**Comment by mtbc** [comment]
Ah, of course! Does this PR automagically remove the same comment in `omero/sysadmins/unix/walkthrough/setup_postgres.sh`?

**Comment by manics** [comment]
It will once I re-open https://github.com/openmicroscopy/ome-documentation/pull/1157

See `omero/autogen_docs` https://github.com/openmicroscopy/ome-documentation/pull/1157/files#diff-915398ad88f8840f783ff8b07fe36fd7 if you're interested

**Comment by mtbc** [comment]
Aha, thank you. :+1:

**Pull request merged**
