### PR TITLE
Ubuntu rename

### PR DESCRIPTION
**Pull request by jburel**
Remove ``1404`` from the step files used for Debian and ubuntu1604
The walkthroughs will now also be built via travis 
to make sure the changes are propagated correctly

To test:
  * Check that travis is green

https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs-autogen/463/ fixed in this PR

### CODE REVIEW

**Comment by will-moore** [comment]
Travis is green but it seems build is still failing at https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs-autogen/464/

**Comment by will-moore** [comment]
You still mention ```1404``` in linux/autogenerate.sh
Does this need updating?
```
function generate_all() {
	values=(centos7 centos6_py27 centos6_py27_ius ubuntu1404 debian8 ubuntu1604)
```

**Comment by will-moore** [comment]
Not sure I understand the scope of these changes (remove ALL support for 1404?) but files are still around named e.g. ``` linux/install_ubuntu1404_nginx.sh``` and this references others like ```step01_ubuntu1404_pg_deps.sh``` and ``` step05_ubuntu1404_nginx.sh``` ?

**Comment by jburel** [comment]
We still support 14.04 i.e. ``linux/install_ubuntu1404_nginx.sh``
the common steps for ubuntu14.04, ubuntu16.04, debian8 are renamed ``stepXX_ubuntu_xx.sh``
For the steps specific to a version e.g. ```step01_ubuntu1404_pg_deps.sh``` , we keep the version in the file name

**Comment by jburel** [comment]
the failure in autogen doc will be fixed only when the PR is merged.
``ubuntu14.04 install`` file and generation of the walkthrough for 14.04 must be kept.

**Comment by will-moore** [comment]
OK, understood. Good to merge then.

**Comment by jburel** [comment]
Merging so we can test the doc

**Pull request merged**
