### PR TITLE
Install Django 1.6.11 as a Python dependency

### PR DESCRIPTION
**Pull request by sbesson**
This should allow to deploy OMERO.web 5.2.0 on a Windows environment

The corresponding whl file is under `/ome/team/sbesson/omero-install/windows/python-2.7.9` 

/cc @manics @aleksandra-tarkowska

### CODE REVIEW

**Comment by manics** [comment]
I ended up rebuilding my Windows image which required reinstalling RVM... and ruby.... I'll get to this tomorrow.

**Comment by manics** [comment]
It installs django:

```
>C:\OMERO.server>python -c "import django; print django.__version__"
1.8.5
```

and I've started OMERO.web (OMERO-DEV-latest) on IIS:

```
>bin\omero version
5.2.0-m1-217-4aaf042-ice35-b128

>bin\omero web iis`
...
616 static files copied to 'C:\OMERO.server\lib\python\omeroweb\static', 2 post-
processed.
Clearing expired sessions. This may take some time...
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 a
nd the TEMPLATES dictionary takes precedence. You must put the values of the fol
lowing settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_CONTEX
T_PROCESSORS.
[OK]
Configured Virtual Directory: /omero
Configured Virtual Directory: /static
Installation complete.
```

but http://localhost/omero/ gives a 500 error

**Comment by sbesson** [comment]
Last commit should install `Django 1.6` on Windows until we have the support for Django 1.8

**Comment by joshmoore** [comment]
The change looks fine. Not sure it's worth more time investment until this can be automated; see https://trello.com/c/EEsxskzP/18-omero-install-windows

**Pull request merged**
