### PR TITLE
Python 3.6 ubuntu1604

### PR DESCRIPTION
**Pull request by jburel**
* Add option to install 3.6
The installation is tested via Travis

### CODE REVIEW

**Comment by dominikl** [comment]
Works fine. When run with `PYTHONVER=py36` Python 3.6 is installed additionally, if omitted only 3.5 is installed. However, even if 3.6 is installed the default Python seems to link to 3.5:
```
omero-server@38ccff9906cd:/$ python3 --version
Python 3.5.2
```
Don't know if that's a problem and/or intended.

**Comment by dominikl** [comment]
Sorry, that's the system python, I didn't activate the omero-server virtual env. Testing again...

**Comment by dominikl** [comment]
👍 Using the virtualenv:
```
(venv3) omero-server@557460d0c9fd:/opt/omero/server$ python --version
Python 3.6.10
```

**Comment by jburel** [comment]
@dominikl one could use alternatives to switch python version, I did not want to go that route since we do not know what people want to do

**Comment by dominikl** [comment]
Sure, makes sense!

**Comment by dominikl** [comment]
With `PYTHONVER=py36`:
```
(venv3) root@c4e37797c007:/# python --version
Python 3.6.9
```
👍 
Wonder if that could be a general approach to install it from source, in order to be independant from the system's python version.  Just takes quite a while to compile.

**Comment by jburel** [comment]
installing from source takes a lot of time and many people will avoid it if they can.
That's also why we have built wheels for the Python binding for Ice

**Comment by jburel** [comment]
The last commit cap the version of numpy for ubuntu 16.04+python 3.5 
this could be moved to omero-server if we are happy to cap the version on 16.04 for both 3.5 and 3.6
cc @joshmoore

**Comment by dominikl** [comment]
Looks good to me 👍

**Pull request merged**
