### PR TITLE
Redis

### PR DESCRIPTION
**Pull request by atarkowska**
This PR test redis installation on Unix, see doc https://github.com/openmicroscopy/ome-documentation/pull/1431

To test:

```
$ ENV=(centos7_nginx|centos7_apache24)
$ WEBSESSION=true ./docker-build.sh $ENV
OSX: $ WEBSESSION=true DMNAME=dev ./test_services.sh # docker machine can be obtained from docker-machine ls
UNIX: $ WEBSESSION=true ./test_services.sh
$ WEBSESSION=true ./test_services.sh

# test REDIS manually
OSX: $ docker run -d --privileged -p 8888:80 --name omeroinstall omero_install_test_$ENV
UNIX: $ docker run -d --name omeroinstall -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /run omero_install_test_$ENV
# wait 1 min until omero accept connections
$ docker exec -it omeroinstall /bin/bash -c "service redis status"
$ docker exec -it omeroinstall bash
[root@42c0852b59ef /]# redis-cli
127.0.0.1:6379> PING
PONG
127.0.0.1:6379> MONITOR
OK
(here you will see the content)
```

open another console, (if you use docker-machine `eval $(docker-machine env dev)`)

```
$ WEB_HOST=$(docker-machine ip dev):8888 ./test_login_to_web.sh
```

while script is logging in, on redis monitor you will see:

```
1460330344.663488 [0 127.0.0.1:55185] "SELECT" "1"
1460330344.663733 [1 127.0.0.1:55185] "EXISTS" ":1:django.contrib.sessions.cachehd4570rlkho9e6ngpy3qr8cvakpzpk1b"
1460330344.664056 [1 127.0.0.1:55185] "SETNX" ":1:django.contrib.sessions.cachehd4570rlkho9e6ngpy3qr8cvakpzpk1b" "\x80\x02}q\x01U\tconnectorq\x02comeroweb.connector\nConnector\nq\x03)\x81q\x04}q\x05(U\tis_secureq\x06\x89U\tserver_idq\aX\x01\x00\x00\x001U\auser_idq\b\x8a\x00U\x11omero_session_keyq\tU$162d57e5-34db-47b1-93b7-4262258d2b23q\nU\tis_publicq\x0b\x89ubs."
1460330344.664377 [1 127.0.0.1:55185] "EXPIRE" ":1:django.contrib.sessions.cachehd4570rlkho9e6ngpy3qr8cvakpzpk1b" "86400"
1460330344.681574 [1 127.0.0.1:55164] "GET" ":1:django.contrib.sessions.cachehd4570rlkho9e6ngpy3qr8cvakpzpk1b"
1460330344.760156 [1 127.0.0.1:55164] "DEL" ":1:django.contrib.sessions.cachehd4570rlkho9e6ngpy3qr8cvakpzpk1b"
```

TESTED via travis https://travis-ci.org/ome/omero-install/builds/123777478
- https://travis-ci.org/ome/omero-install/jobs/123777479#L4457
- https://travis-ci.org/ome/omero-install/jobs/123777479#L4581

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper#137](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/137/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/137/consoleText) for more details.
Possible conflicts:
- PR #94 jburel 'Parameters'
  - linux/install_centos7_nginx.sh
  - linux/install_centos7_apache24.sh
  - linux/install_centos6_py27_apache24.sh

**Comment by joshmoore** [comment]
NB: I assume testing of this occurs according to https://github.com/openmicroscopy/devspace/pull/20#issuecomment-202329949

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper#138](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/138/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/138/consoleText) for more details.
Possible conflicts:
- PR #94 jburel 'Parameters'
  - linux/install_centos7_nginx.sh
  - linux/install_centos7_apache24.sh
  - linux/install_centos6_py27_apache24.sh

**Comment by jburel** [comment]
in `step01_centos6_py27_ius_deps_experimental.sh`

```
+set +u
 +source /opt/rh/python27/enable
 +set -u
```

is not correct. This command is for scl python
for ius you will have to use virtualenv

**Comment by jburel** [comment]
I will also break it into 2 PRs: one for linux, one for OSX

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper#139](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/139/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/139/consoleText) for more details.
Possible conflicts:
- PR #94 jburel 'Parameters'
  - linux/install_centos7_nginx.sh
  - linux/install_centos7_apache24.sh
  - linux/install_centos6_py27_apache24.sh

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper#140](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/140/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/140/consoleText) for more details.
Possible conflicts:
- PR #94 jburel 'Parameters'
  - linux/install_centos7_nginx.sh
  - linux/install_centos7_apache24.sh
  - linux/install_centos6_py27_apache24.sh

**Comment by atarkowska** [comment]
Excluding for now as we need first #99

**Comment by atarkowska** [comment]
osx move to https://github.com/ome/omero-install/pull/101

**Comment by jburel** [comment]
@aleksandra-tarkowska: the target of this work is more for 5.3 unless I misunderstood, so it might be time to create a new branch for that repo
We also want to adjust the parameters strategy since we have a large number of them and probably more to come e.g. python/ This is outside the scope of this PR.

**Comment by atarkowska** [comment]
@jburel I thought 5.2.3 as https://trello.com/c/QBRpCUUQ/43-nightshade-deployment-issues, has that changed?

**Comment by manics** [comment]
Am I right in thinking this doesn't require any code changes to OMERO.server/OMERO.web, just setting some existing config properties? If so I don't think it's worth creating another branch since future PRs will need rebasing.

**Comment by jburel** [comment]
Discussed with @aleksandra-tarkowska, I lost track of which milestone we were thinking to have it.
Ola is going to adjust the name so it is clearer.

**Comment by jburel** [comment]
`step01_centos6_py27_deps_experimental.sh` and `step01_centos6_py27_ius_deps_experimental.sh` could probably be merged passing the python version used similar to  `step05_2_experimentalconfig.sh`

**Comment by jburel** [comment]
Are you planning to start redis when running the image if experimental is true?

**Comment by atarkowska** [comment]
> Are you planning to start redis when running the image if experimental is true?

@jburel is that not what https://github.com/ome/omero-install/pull/95/files#diff-1337d8f4ef8c1d8af22cc375046c102cR7 is doing?

**Comment by jburel** [comment]
```
docker run --rm -it -p 8080:80 -p 4063:4063 -p 4064:4064 omero_install_test_centos6_py27_nginx
Starting postgresql-9.4 service:                           [  OK  ]
Starting crond:                                            [  OK  ]
Starting omero: OMERO.server
Starting nginx:                                            [  OK  ]
Starting omero-web: OMERO.web
[root@e42b9876b56c /]# service redis status
redis-server dead but pid file exists
[root@e42b9876b56c /]# service redis start
Starting redis-server:                                     [  OK  ]
```

redis not started
you will have to adjust the `run.sh` files

**Comment by atarkowska** [comment]
sorry I only tested centos7

**Comment by jburel** [comment]
No problem

**Comment by atarkowska** [comment]
> Am I right in thinking this doesn't require any code changes to OMERO.server/OMERO.web, just setting some existing config properties?

yes this is purely config

>  If so I don't think it's worth creating another branch since future PRs will need rebasing.

@manics what do you mean exactly ?

**Comment by jburel** [comment]
>  If so I don't think it's worth creating another branch since future PRs will need rebasing.
> @aleksandra-tarkowska: that was a response to my comment. Nothing to do.

**Comment by jburel** [comment]
The walkthrough files should not be committed to this repo neither should the omero-install-test.zip files

**Comment by jburel** [comment]
9349836 will have to be reverted.

**Comment by atarkowska** [comment]
- walkthrough removed
- travis revered, reference to this build in the description

**Comment by jburel** [comment]
linux/test/centos6_py27_ius_nginx/omero-install-test.zip
linux/test/centos7_nginx/omero-install-test.zip
to be removed too

**Comment by atarkowska** [comment]
> you will have to adjust the run.sh files

@jburel redis is now started in `run.sh`

**Comment by jburel** [comment]
I have opened a PR  against this branch so redis server is not started by default.
Could you also add a section on the README about web session ?

**Comment by manics** [comment]
Is Redis supported on all platforms? Or would it be easier to support just the latest (centos 7)?

**Comment by atarkowska** [comment]
redis is supported for python 2.7 only

**Comment by jburel** [comment]
very minor: CentOS7 => CentOS 7

**Comment by atarkowska** [comment]
done

**Comment by jburel** [comment]
Thanks @aleksandra-tarkowska merging

**Pull request merged**
