### PR TITLE
Added docker file for debian8 apache24

### PR DESCRIPTION
**Pull request by dominikl**
Docker file for debian8 apache24 installation; just runs the according ubuntu installation scripts on debian:jessie base image.

### CODE REVIEW

**Comment by ximenesuk** [comment]
I am pretty certain this is unrelated to this PR but while testing I had the following error twice:

```
$ sh docker-build.sh debian8_apache24
…
Get:330 http://httpredir.debian.org/debian/ jessie/main python-scipy amd64 0.14.0-2 [8144 kB]
Fetched 213 MB in 48s (4430 kB/s)
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/r/rename/rename_0.20-3_all.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c cd omero-install-test &&     bash install_ubuntu1404_apache24.sh &&     bash docker_shutdown_ubuntu1404.sh' returned a non-zero code: 100
```

This is similar to what @jburel saw at https://github.com/ome/omero-install/pull/56#issuecomment-158406001

Is this just network flakiness? Or is there some specific `debian` issue?

**Comment by ximenesuk** [comment]
The other two attempts to build this have both stalled at:

```
...
Setting up ca-certificates-java (20140324) ...
```

**Comment by ximenesuk** [comment]
Adding to the comment above I get the same stall on `ubuntu1404`

```
...
Setting up ca-certificates-java (20130815ubuntu1) ...
```

in both cases is happens for `nginx` and `apache24`

**Comment by ximenesuk** [comment]
See https://github.com/docker/docker/issues/18180

However, I am using `1.9.0` so I am not sure how relevant this issue is - though it is remarkably similar!

**Comment by jburel** [comment]
Did not have time to test it today. I will do it tomorrow

**Comment by dominikl** [comment]
Can't get travis green, but PR works locally when omerodev is used. This should actually do the trick for travis, no idea why it doesn't work: https://github.com/dominikl/omero-install/commit/492f6f14198e4edc97ddf5f08bcdcb4fe3472bfc#diff-354f30a63fb0907d4ad57269548329e3R16

**Comment by dominikl** [comment]
Ok, this time debian-apache failed with am apt download issue and debian-nginx failed to install "libjpeg8-dev". Will try to fix the "libjpeg8-dev" issue and retrigger the job.

**Comment by dominikl** [comment]
Now I can't build any docker image, hanging at `Setting up ca-certificates-java (20140324) ...`. Don't know what's wrong with my docker/virtualbox. Can try another round of cleaning my laptop from any docker related stuff and reinstalling everything again. In case that doesn't help either, I'll probably have to remove the docker files for debian again.

**Comment by dominikl** [comment]
Unfortunately debian has renamed `libjpeg8-dev` into `libjpeg62-turbo-dev`, so I can't just use all the ubuntu scripts, needed an adapted one for installing the dependencies `step01_debian8_deps.sh`.

**Comment by manics** [comment]
Might be a bug (or an out-of-sync mirror) since Debian is meant to be stable. You can get multiple names for the same package for compatibility. Try searching the Debian bug tracker, or wait a few days and see if the mirrors are corrected.

**Comment by dominikl** [comment]
I think it's fine, in jessie (stable) the package is called [libjpeg62-turbo-dev](https://packages.debian.org/jessie/libjpeg62-turbo-dev), strangely it's called [libjpeg8-dev](https://packages.debian.org/sid/libjpeg8-dev) in previous releases and in unstable repository. Just wonder why the debian docker actually worked a couple of weeks ago with `libjpeg8-dev`.

**Comment by manics** [comment]
Have you tried rebuilding with `docker pull debian:jessie; docker build --no-cache ...`?

**Comment by dominikl** [comment]
Well, I removed all docker containers and images and reinstalled docker again a couple of times, because I had problems with the latest docker release (always hanging at "generating ca-certificates..." step), this should have had the same effect I guess.

**Comment by dominikl** [comment]
This also fixes a general problem with debian8 build, so ideally both _nginx_ and _apache_ should be **tested**. Note: For apache working without manual adjustment, #76 has to be included as well.

**Comment by jburel** [comment]
Both nginx and apache, works.
Merging, we can always revisit later on
I have another PR reviewing the usage of OMEROVER so it can be modified via the command line.

**Pull request merged**
