### PR TITLE
wait until server fully initialize

### PR DESCRIPTION
**Pull request by atarkowska**
attempt to fix homebrew https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-homebrew/

### CODE REVIEW

**Comment by joshmoore** [comment]
A heads up that `start` already calls `waitup` internally: https://github.com/openmicroscopy/openmicroscopy/blob/v5.2.2/components/tools/OmeroPy/src/omero/plugins/admin.py#L759

So if this works, it will be because it's pausing for a short period of time. Likely what we need is a proper `waitup --login` or something that requires much more.

**Comment by atarkowska** [comment]
true, sorry I thought other way around, lets see if the same issue appear even log says is fully initialized

**Comment by atarkowska** [comment]
looks like that was one off failure. I need to admit I saw it locally occasionally on mac few times

**Comment by jburel** [comment]
Closing this PR I will cherry-pick the commits

**Comment by jburel** [comment]
See https://github.com/ome/omero-install/pull/143

**Pull request closed without merging**
