### PR TITLE
apps

### PR DESCRIPTION
**Pull request by jburel**
remove web apps section

This is no longer used and out of date.
This was initially introduced if someone wanted it to test apps locally when apps were not pip installed. 
@pwalczysko was using it at the time but no longer does.
App evaluations/deployment are now done on other server e.g. outreach

### CODE REVIEW

**Comment by joshmoore** [comment]
What's the driver for this, @jburel ? (Sorry, I may have missed a chat)

**Comment by jburel** [comment]
This is out of date and the approach to install the apps has changed.
So no real need to keep it there

**Comment by will-moore** [comment]
Changes *look* OK. Does it need a build for regression-testing?
Building with ```$ OMEROVER=OMERO-DEV-merge-build ./docker-build.sh debian9_nginx``` for testing https://github.com/ome/omero-install/pull/197 seemed to build OK (although I couldn't connect because of changes in that PR).

**Comment by jburel** [comment]
do you mean a travis build?

**Comment by jburel** [comment]
Discussed with @will-moore, travis is green those changes have not affected the general instructions
None of the code removed is used in our documentation.
Merging

**Pull request merged**
