### PR TITLE
Bump Ice 3.5.1 build numbers for Windows installation

### PR DESCRIPTION
**Pull request by sbesson**
This should update the installation scripts to use the latest build of the Ice 3.5 packages for Windows.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
The changes look fine to me.

**Comment by sbesson** [comment]
With the release of the latest Ice 3.5.1 packages, this should be mergeable now /cc @manics @joshmoore

**Comment by manics** [comment]
If anyone's got a VM handy they could test it properly with the packages on squig... if not just merge?

As an aside I was thinking of converting this repo to use git-lfs, though last time I checked the size limits were too low

**Comment by joshmoore** [comment]
* just merging
 * re: `lfs` seems a bit early for that.

**Pull request merged**
