### PR TITLE
Use ~/OMERO.data as data.dir for homebrew script

### PR DESCRIPTION
**Pull request by will-moore**
As suggested https://github.com/openmicroscopy/ome-documentation/pull/1394#issuecomment-179870643 applying the same change here as made to the homebrew install docs.

### CODE REVIEW

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/99/ is certainly good with this PR included. Should we try removing the `OMERO_DATA_DIR` variable overriding in the job to test its default value?

**Comment by jburel** [comment]
@sbesson  It will be good to try the default value.

**Comment by sbesson** [comment]
Done. To be tested by tomorrow's build.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/100/ is definitely green with

```
+ export OMERO_DATA_DIR=/Users/hudson/OMERO.data
+ OMERO_DATA_DIR=/Users/hudson/OMERO.data
```

**Comment by hflynn** [comment]
Does that mean I'm good to merge the docs PR for this @sbesson ?

**Comment by sbesson** [comment]
I would confirm with @jburel but the Travis failure is unrelated and the CI job properly tests the change suggested in the doc PR.

**Comment by hflynn** [comment]
Ah okay, I'll wait on this being merged to be on the safe side.

**Comment by jburel** [comment]
All travis builds are currently failing. I need to look at it.
Not specific to this PR. 
@hflynn merging so you can move forward

**Pull request merged**
