### PR TITLE
Create docker for Ubuntu1404 with apache24

### PR DESCRIPTION
**Pull request by ximenesuk**
This adds the apache 2.4 web deployment to the ubuntu 14.04 installation.

The standard build and docker start process should provide a running omero system. Note though that the web will not be functioning correctly, see https://github.com/manics/openmicroscopy/commit/d61d63a81df5023d202e1e5bfcfd9c292a6fa6d2 To run web:

 + modify `/etc/apache2/sites-available/omero-web.conf`
 + restart apache, `service apache2 restart`

the webclient will then be automatically available.

### CODE REVIEW

**Comment by ximenesuk** [comment]
I'm not sure if it makes sense to get this PR in first or do the script renaming and then rebase this PR.

**Comment by joshmoore** [comment]
Happy to leave that to whoever is doing the renaming.

**Comment by dominikl** [comment]
I checked out your branch and tried to build the docker image, got

```cp: cannot stat 'setup_omero_apache24.sh': No such file or directory
The command '/bin/sh -c cd omero-install-test && bash install-ubuntu1404-apache.sh' returned a non-zero code: 1```

There's no ```setup_omero_apache24.sh```. I guess that's in another PR/branch? Is there some kind of "merge build" I can use the test the PR?

**Comment by ximenesuk** [comment]
@dominikl yes, the relevant PR is https://github.com/ome/omero-install/pull/50 but it has now been merged.

If you checkout master and merge my branche you should be good to test.

**Comment by dominikl** [comment]
Ok, I checked out the ome-install master branch and merged your branch onto it (correct?).
Now I get:
```
usage: OMERO.server/bin/omero web config [-h] [--http HTTP]
                                         [--max-body-size MAX_BODY_SIZE]
                                         {nginx,nginx-development,apache}
OMERO.server/bin/omero web config: error: argument type: invalid choice: 'apache24'

choose from:
	apache, nginx, nginx-development
The command '/bin/sh -c cd omero-install-test && bash install-ubuntu1404-apache.sh' returned a non-zero code: 2
```

**Comment by jburel** [comment]
@dominikl: you then need to set ```OMEROVER=omerodev``` in ```install-ubuntu1404-apache.sh``` (default is ```OMEROVER=omero```)

**Comment by jburel** [comment]
The ```service apache2 start``` is invoked twice i.e.  in ```run.sh``` and ```setup_apache_ubuntu1404.sh```. Is that intended?

**Comment by jburel** [comment]
The following message
```
apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
```
 is displayed when starting apache2. This can removed by adding to ```setup_apache_ubuntu1404.sh```
```
echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf
a2enconf fqdn
```

**Comment by jburel** [comment]
I will add to the README under ```linux/test``` the instructions 
i.e. edit WSGISocketPrefix run/wsgi, reload apache, start web. or add link to the documentation for edit part so it is clearer that not everything is "ready to go" after running ```docker run ...```

I connected to server using web

**Comment by jburel** [comment]
webapacheubuntu1404

**Comment by ximenesuk** [comment]
Re https://github.com/ome/omero-install/pull/52#issuecomment-157885157 most of the other scripts start the web deployment service twice two. I was, to get this in, mirroring how the other scripts worked.

Re https://github.com/ome/omero-install/pull/52#issuecomment-157885835, same here this message is displayed by other scripts too, same reason as above.

Fo these two issues I would prefer to get this merged if possible, do the renaming, and then review the scripts to remove redundant lines, fix warning messages and add arguments.

Re https://github.com/ome/omero-install/pull/52#issuecomment-157894072 It would be better if this issue was fixed int the scripts. @manics suggested a `sed` step as the content of the file is predicatble but maybe there is a solution when the configuration file is first generated? Though changing the README in the short term certainly makes sense.

**Comment by jburel** [comment]
I agree that the cleaning should be done in follow up PRs since other scripts need to be reviewed.
Discussed with @ximenesuk: Readme to be updated in this PR then we will be ready to merge

**Comment by manics** [comment]
`run.sh` is only used by the Dockerfile for automated testing, it's not intended for use anywhere else.

**Comment by jburel** [comment]
Thanks @manics for the clarification

**Comment by jburel** [comment]
Merging so we can move forward with the renaming.
Thanks @ximenesuk

**Pull request merged**
